      MODULE FLAGS

      INTEGER RESUMEFLAG
      INTEGER SAVERESUMEFLAG 
      INTEGER SOILINIFLAG
      INTEGER NRSOILAYEREADFLAG
!> DEC 31/18 - DGP NUDGESDEPFLAG
      integer :: NUDGESDEPFLAG = 0
      INTEGER RELFLG
      INTEGER SUBBASINFLAG
      INTEGER R2COUTPUTFLAG
      INTEGER OBJFNFLAG
      INTEGER WINDOWSIZEFLAG
      INTEGER WINDOWSPACINGFLAG
      INTEGER METRICSSTATSOUTFLAG
      INTEGER METRICSFILTEROBSFLAG
      INTEGER METRICSSPINUP
      INTEGER METRICSINCLUDESPINUP
      INTEGER FROZENSOILINFILFLAG
!> JAN 30/14 - KCK     ADDED LOCATIONFLAG
      INTEGER LOCATIONFLAG

!> JUL 17/14 -GSA- GET FIELDS BALANCEs
      INTEGER OUTFIELDSFLAG

!> OCT 16/14 -GSA- GET Geothermal flux
      INTEGER GGEOFLAG
!> NOV 18/14 -GSA- Variable in/out file names
      INTEGER VARIABLEFILESFLAG

      integer :: BASINAVGEVPFILEFLAG = 0
      INTEGER :: BASINSWEOUTFLAG = 0
!> FEB 8/17 -GSA- Reservoir
      INTEGER RESERVOIRFLAG

      END
