      MODULE FLAGS
      
      INTEGER BASINSHORTWAVEFLAG
      INTEGER BASINLONGWAVEFLAG
      INTEGER BASINRAINFLAG 
      INTEGER BASINTEMPERATUREFLAG
      INTEGER BASINWINDFLAG
      INTEGER BASINPRESFLAG 
      INTEGER BASINHUMIDITYFLAG
      INTEGER HOURLYFLAG
      INTEGER RESUMEFLAG
      INTEGER SAVERESUMEFLAG 
      INTEGER SHDFILEFLAG
      INTEGER SOILINIFLAG
      INTEGER STREAMFLOWFLAG
      INTEGER CONFLAGS
      INTEGER RELFLG
      INTEGER OPTFLAGS
      INTEGER PREEMPTIONFLAG
      INTEGER INTERPOLATIONFLAG
      INTEGER SUBBASINFLAG
      INTEGER TESTCSVFLAG
      INTEGER R2COUTPUTFLAG
      INTEGER OBJFNFLAG
      INTEGER AUTOCALIBRATIONFLAG
      INTEGER WINDOWSIZEFLAG
      INTEGER WINDOWSPACINGFLAG
      INTEGER METRICSSTATSOUTFLAG
      INTEGER METRICSFILTEROBSFLAG
      INTEGER METRICSSPINUP
      INTEGER METRICSINCLUDESPINUP
      INTEGER FROZENSOILINFILFLAG
      INTEGER PRINTRFFR2CFILEFLAG
      INTEGER PRINTRCHR2CFILEFLAG
!      INTEGER PRINTLKGR2CFILEFLAG
!> JUN 03/11 - DGP      ADDED FOR WATDRN3
!> JUL 10/11 - DGP      WD3FLOW
!> AUG 19/11 - DGP      WD3BKFC
      INTEGER WD3
      INTEGER WD3NEWFILE
      INTEGER WD3FLOW
      INTEGER WD3BKFC
      INTEGER PBSMFLAG
!> JAN 30/14 - KCK     ADDED LOCATIONFLAG
      INTEGER LOCATIONFLAG

!> JUL 17/14 -GSA- GET FIELDS BALANCEs
      INTEGER OUTFIELDSFLAG

!> OCT 16/14 -GSA- GET Geothermal flux
      INTEGER GGEOFLAG
!> NOV 18/14 -GSA- Variable in/out file names
      INTEGER VARIABLEFILESFLAG

      INTEGER BASINBALANCEOUTFLAG
      INTEGER MODELINFOOUTFLAG
      INTEGER STREAMFLOWOUTFLAG
      INTEGER BASINSWEOUTFLAG

      END
