      MODULE FLAGS
      
      INTEGER BASINSHORTWAVEFLAG
      INTEGER BASINLONGWAVEFLAG
      INTEGER BASINRAINFLAG 
      INTEGER BASINTEMPERATUREFLAG
      INTEGER BASINWINDFLAG
      INTEGER BASINPRESFLAG 
      INTEGER BASINHUMIDITYFLAG
      INTEGER HOURLYFLAG
      INTEGER RESUMEFLAG
      INTEGER SAVERESUMEFLAG 
      INTEGER SHDFILEFLAG
      INTEGER SOILINIFLAG
      INTEGER STREAMFLOWFLAG
      INTEGER CONFLAGS
      INTEGER RELFLG
      INTEGER OPTFLAGS
      INTEGER PREEMPTIONFLAG
      INTEGER INTERPOLATIONFLAG
      INTEGER SUBBASINFLAG
      INTEGER TESTCSVFLAG
      INTEGER R2COUTPUTFLAG
      INTEGER OBJFNFLAG
      INTEGER AUTOCALIBRATIONFLAG
      INTEGER WINDOWSIZEFLAG
      INTEGER WINDOWSPACINGFLAG
      INTEGER FROZENSOILINFILFLAG

!> JUN 03/11 - DGP      ADDED FOR WATDRN3
!> JUL 10/11 - DGP      WD3FLOW
      INTEGER WD3
      INTEGER WD3NEWFILE
      INTEGER WD3FLOW

      END
