SUBROUTINE GATHER(NA,NML,ILMOS,GRD,GAT)

!SIMPLE VERSION OF THE CLASSG SUBROUTINE.
    
    INTEGER NA, NML
    INTEGER ILMOS(NML)
    REAL    GRD(NA), GAT(NML)
    
    INTEGER K
    
    DO K = 1,NML
       GAT(K) = GRD(ILMOS(K))
   ENDDO

END SUBROUTINE
