SUBROUTINE TEST_CSV(NTYPE,NML,NA,ILMOS,GAT,GRU)

!CHECKS PROPER DISTRIBUTION OF THE CSV FORCING DATA ON EACH GRID       .

    INTEGER NTYPE,NML,NA
    INTEGER ILMOS(NML)
    REAL    GAT(NML),GRU(NTYPE)
    REAL    ERR(NTYPE)
    REAL    ERRMAX, ERRTOL
 
 !SET ERROR TOLERANCE TO ROUNDING ERROR   
    ERRTOL = 1.0E-17
 
 !CHECK PROPER DISTRIBUTION OF THE CSV FORCING DATA ON EACH GRID   
    IF(NA > 1)THEN
        DO I = 1, NML-NTYPE
            IF(GAT(I) .NE. GAT(I+NTYPE))THEN
                PRINT*,"FORCING DATA REDISTRIBUTION AT GRID ", ILMOS(I), " IS WRONG."
                PAUSE
                STOP
            ENDIF
        ENDDO
    ENDIF
 
 !COMPARE THE FIRST GRID GRU VALUES WITH THE CORRESPONDING VALUES IN THE CSV FILE.   
    DO J = 1,NTYPE
       ERR(J) = ABS(GAT(J)-GRU(J))
    ENDDO

!COMPUTE THE MAX DIFFERENCE - IT SHOULD NOT BE GREATER THAN ROUNDING ERROR
    ERRMAX = MAXVAL(ERR)
    IF(ERRMAX < ERRTOL)THEN
       PRINT*,"MAXIMUM ERROR: ",ERRMAX," ERROR TOLERANCE: ", ERRTOL
       PRINT*,"TEST: OK"
    ELSE
       PRINT*,"MAXIMUM ERROR: ",ERRMAX," ERROR TOLERANCE: ", ERRTOL
       PRINT*,"TEST: NOT OK"
       PAUSE
       STOP
    ENDIF

END SUBROUTINE