SUBROUTINE WRITE_CMEM_R2C_HEADER(NMTEST,coordsys1,datum1,zone1,XORIGIN,YORIGIN, &
								XDELTA,YDELTA,XCOUNT,YCOUNT)

USE MESH_CMEM_MODULE, ONLY: CMEMFLAG, CMEMR2COUTPUTFLAG, CMEMTHETA, &
							GRD_CMEM, GAT_CMEM, GRDGAT_CMEM, &
							R2C_ATTRIBUTES_CMEM, R2CFILEUNITSTART_CMEM, &
							FRAME_NO_CMEM, NR2CFILES_CMEM, NR2C_CMEM, &
							DELTR2C_CMEM,NR2CSTATES_CMEM

IMPLICIT NONE


INTEGER :: IOS, PAS, I, J, K
LOGICAL :: R2COUTPUT
character(10) coordsys1,datum1,zone1
real xorigin,yorigin,xdelta,ydelta
INTEGER XCOUNT,YCOUNT, NMTEST
CHARACTER*50, DIMENSION(3) :: att_temp

!> Open and read in values from r2c_output_cmem.txt
!********************************************************************************
NR2CFILES_CMEM = 0
IF(CMEMR2COUTPUTFLAG .GE. 1) THEN
  INQUIRE(FILE='r2c_output_cmem.txt', EXIST = R2COUTPUT)
  IF(R2COUTPUT) THEN
      OPEN(57, FILE='r2c_output_cmem.txt')
	  READ(57,*,IOSTAT=IOS) NR2C_CMEM, DELTR2C_CMEM

	  !> NUMBER OF FILES * NUMBER OF INCIDENCE ANGLES
	  NR2C_CMEM = NR2C_CMEM*CMEMFLAG 

	  IF(IOS == 0) THEN
	  ALLOCATE(GRD_CMEM(NR2C_CMEM),GAT_CMEM(NR2C_CMEM),GRDGAT_CMEM(NR2C_CMEM), &
				R2C_ATTRIBUTES_CMEM(NR2C_CMEM,3),STAT=PAS)
	  IF(PAS /= 0)THEN
           PRINT*,'ALLOCATION ERROR: CHECK THE VALUE OF THE FIRST ', &
                  'RECORD AT THE FIRST LINE IN THE r2c_output.txt FILE. ', &
                  'IT SHOULD BE AN INTEGER VALUE (GREATER THAN 0).'
           STOP
         ENDIF !> PAS/=0
      ENDIF			! IOS == 0
	  IF(IOS /=0 .OR. MOD(DELTR2C_CMEM,30) /=0)THEN
		WRITE(6,9002)
		STOP
	  ENDIF !IOS/=0 OR MOD...

	  PRINT*
      PRINT*,'THE FOLLOWING R2C OUTPUT FILES WILL BE WRITTEN:'
I=1
DO WHILE (I .LE. NR2C_CMEM)
          READ(57,*,IOSTAT=IOS)GRD_CMEM(I),GAT_CMEM(I),GRDGAT_CMEM(I),(att_temp(J),J=1,3)
		  		  
		  IF(IOS /= 0)THEN
             PRINT*,'ERROR READING r2c_output.txt FILE AT LINE ', I + 1
             STOP
          ELSE
		   
		   !> EXTRA LOOP OVER ORIGINAL FUNCTION TO ADD IN THE ANGLES

		   DO K = 1,CMEMFLAG
			IF(K>1) THEN
				I = I + 1 !Increment to next point
				GRD_CMEM(I) = GRD_CMEM(I-1)
				GAT_CMEM(I) = GAT_CMEM(I-1)
				GRDGAT_CMEM(I) = GRDGAT_CMEM(I-1)
			ENDIF
		  
		    ! ADD THE ANGLES TO THE ATTRIBUTES
			WRITE(R2C_ATTRIBUTES_CMEM(I,1),'(A,A,I2)') TRIM(att_temp(1)), &
														'_',INT(CMEMTHETA(K)) 
			WRITE(R2C_ATTRIBUTES_CMEM(I,3),'(A,A,I2)') TRIM(att_temp(3)), & 
														'_',INT(CMEMTHETA(K))
			WRITE(R2C_ATTRIBUTES_CMEM(I,2),'(A)') att_temp(2)
		    
		  
            IF(GRD_CMEM(I)==1)THEN
              NR2CFILES_CMEM = NR2CFILES_CMEM + 1
              PRINT*,NR2CFILES_CMEM,' (GRD)    : ',R2C_ATTRIBUTES_CMEM(I,3)
            ENDIF
            IF(GAT_CMEM(I)==1)THEN
              NR2CFILES_CMEM = NR2CFILES_CMEM + 1
              PRINT*,NR2CFILES_CMEM,' (GAT)    : ',R2C_ATTRIBUTES_CMEM(I,3)
            ENDIF
            IF(GRDGAT_CMEM(I)==1)THEN
              NR2CFILES_CMEM = NR2CFILES_CMEM + 1
              PRINT*,NR2CFILES_CMEM,' (GRDGAT) : ',R2C_ATTRIBUTES_CMEM(I,3)
            ENDIF
			
           ENDDO ! K=1,CMEMFLAG
		   
         ENDIF ! IOS/=0 THEN
		 I = I + 1
		 
      ENDDO ! WHILE
      CLOSE(57)
   ELSE
      PRINT*
      PRINT*,"r2c_output_cmem.txt FILE DOESN'T EXIST. ", &
             "CMEMR2COUTPUTFLAG SHOULD BE SET TO ZERO IF R2C OUTPUTS ARE NOT NEEDED."
      PRINT*
      STOP
   ENDIF !R2COUTPUT
ENDIF !CMEMR2COUTPUTFLAG


!> WRITE THE HEADER FOR R2C FILES:

IF(NR2CFILES_CMEM > 0)THEN

 CALL WRITE_R2C_HEADER(NMTEST,NR2C_CMEM,NR2CFILES_CMEM,GRD_CMEM,GAT_CMEM,GRDGAT_CMEM, &
					   R2C_ATTRIBUTES_CMEM, R2CFILEUNITSTART_CMEM,NR2CSTATES_CMEM,coordsys1,datum1,zone1,   &
                       XORIGIN,YORIGIN,XDELTA,YDELTA,XCOUNT,YCOUNT)
ENDIF

FRAME_NO_CMEM = 1

9002 FORMAT('ERROR IN READING r2c_output.txt FILE. ',/, &
            'THE FIRST RECORD AT THE FIRST LINE IS FOR THE NUMBER OF ALL THE ', &
            'VARIABLES LISTED IN THE r2c_output.txt FILE.',/,&
            'THE SECOND RECORD AT THE FIRST LINE IS TIME STEP FOR R2C OUTPUT. ', &
            'IT SHOULD BE AN INTEGER MULTIPLE OF 30. ',/,&
            'THE REMAINING RECORDS SHOULD CONTAIN 3 COLUMNS FOR EACH VARIABLE WITH INTEGER VALUES OF ', &
            'EITHER 0 OR 1 AND 3 COLUMNS CONTAINING INFORMATION ABOUT THE VARIABLES')

END SUBROUTINE WRITE_CMEM_R2C_HEADER