      SUBROUTINE CLASSS(TBARROT,THLQROT,THICROT,GFLXROT,TSFSROT,
     1                  TPNDROT,ZPNDROT,TBASROT,ALBSROT,TSNOROT,
     2                  RHOSROT,SNOROT, TCANROT,RCANROT,SCANROT,
     3                  GROROT, CMAIROT,TACROT, QACROT, WSNOROT,
     4                  ILMOS,JLMOS,IWMOS,JWMOS,
     5                  NML,NL,NM,ILG,IG,IC,ICP1,
     6                  TBARGAT,THLQGAT,THICGAT,GFLXGAT,TSFSGAT,
     7                  TPNDGAT,ZPNDGAT,TBASGAT,ALBSGAT,TSNOGAT,
     8                  RHOSGAT,SNOGAT, TCANGAT,RCANGAT,SCANGAT,
     9                  GROGAT, CMAIGAT,TACGAT, QACGAT, WSNOGAT)
C
C     * OCT 25/11 - M.LAZARE.   REMOVE OPERATIONS ON INTERNAL
C     *                         ROT ARRAYS (NOW DONE DIRECTLY
C     *                         GAT->ROW IN SFCPROC).
C     * OCT 07/11 - M.LAZARE.   REMOVE TSF.
C     * OCT 05/11 - M.LAZARE.   ADD SFCH.
C     * OCT 04/11 - M.LAZARE.   REMOVE ITCT.
C     * MAR 23/06 - D.VERSEGHY. ADD WSNO,FSNO.
C     * MAR 18/05 - D.VERSEGHY. ADDITIONAL VARIABLES.
C     * FEB 18/05 - D.VERSEGHY. ADD "TSFS" VARIABLES.
C     * AUG 05/04 - D.VERSEGHY. ADD NEW DIAGNOSTIC VARIABLES
C     *                         ILMO, UE AND HBL.
C     * AUG 15/02 - D.VERSEGHY. SCATTER OPERATION ON CLASS 
C     *                         VARIABLES.
C
      IMPLICIT NONE
C
C     * INTEGER CONSTANTS.
C
      INTEGER NML,NL,NM,ILG,IG,IC,ICP1,K,L,M
C
C     * LAND SURFACE PROGNOSTIC VARIABLES.
C
      REAL    TBARROT(NL,NM,IG), THLQROT(NL,NM,IG), THICROT(NL,NM,IG), 
     1        GFLXROT(NL,NM,IG)

      REAL    TSFSROT(NL,NM,4)

      REAL    TPNDROT(NL,NM),    ZPNDROT(NL,NM),    TBASROT(NL,NM),   
     1        ALBSROT(NL,NM),    TSNOROT(NL,NM),    RHOSROT(NL,NM),   
     2        SNOROT (NL,NM),    TCANROT(NL,NM),    RCANROT(NL,NM),   
     3        SCANROT(NL,NM),    GROROT (NL,NM),    TACROT (NL,NM),  
     4        QACROT (NL,NM),    WSNOROT(NL,NM),    CMAIROT(NL,NM) 
C
      REAL    TBARGAT(ILG,IG),   THLQGAT(ILG,IG),   THICGAT(ILG,IG), 
     1        GFLXGAT(ILG,IG)

      REAL    TSFSGAT(ILG,4)

      REAL    TPNDGAT(ILG),      ZPNDGAT(ILG),      TBASGAT(ILG),   
     1        ALBSGAT(ILG),      TSNOGAT(ILG),      RHOSGAT(ILG),   
     2        SNOGAT (ILG),      TCANGAT(ILG),      RCANGAT(ILG),   
     3        SCANGAT(ILG),      GROGAT (ILG),      TACGAT (ILG),  
     4        QACGAT (ILG),      WSNOGAT(ILG),      CMAIGAT(ILG)
C
C     * GATHER-SCATTER INDEX ARRAYS.
C
      INTEGER  ILMOS (ILG),  JLMOS  (ILG),  IWMOS  (ILG),  JWMOS (ILG)
C----------------------------------------------------------------------
      DO 100 K=1,NML
          TPNDROT(ILMOS(K),JLMOS(K))=TPNDGAT(K)  
          ZPNDROT(ILMOS(K),JLMOS(K))=ZPNDGAT(K)  
          TBASROT(ILMOS(K),JLMOS(K))=TBASGAT(K)  
          ALBSROT(ILMOS(K),JLMOS(K))=ALBSGAT(K)  
          TSNOROT(ILMOS(K),JLMOS(K))=TSNOGAT(K)  
          RHOSROT(ILMOS(K),JLMOS(K))=RHOSGAT(K)  
          SNOROT (ILMOS(K),JLMOS(K))=SNOGAT (K)  
          WSNOROT(ILMOS(K),JLMOS(K))=WSNOGAT(K)  
          TCANROT(ILMOS(K),JLMOS(K))=TCANGAT(K)  
          RCANROT(ILMOS(K),JLMOS(K))=RCANGAT(K)  
          SCANROT(ILMOS(K),JLMOS(K))=SCANGAT(K)  
          GROROT (ILMOS(K),JLMOS(K))=GROGAT (K)  
          TACROT (ILMOS(K),JLMOS(K))=TACGAT (K)  
          QACROT (ILMOS(K),JLMOS(K))=QACGAT (K)  
          CMAIROT(ILMOS(K),JLMOS(K))=CMAIGAT(K)  
  100 CONTINUE
C
      DO 200 L=1,IG
      DO 200 K=1,NML
          TBARROT(ILMOS(K),JLMOS(K),L)=TBARGAT(K,L)
          THLQROT(ILMOS(K),JLMOS(K),L)=THLQGAT(K,L)
          THICROT(ILMOS(K),JLMOS(K),L)=THICGAT(K,L)
          GFLXROT(ILMOS(K),JLMOS(K),L)=GFLXGAT(K,L)
  200 CONTINUE
C
      DO 300 L=1,4
      DO 300 K=1,NML
          TSFSROT(ILMOS(K),JLMOS(K),L)=TSFSGAT(K,L)
  300 CONTINUE
C
      RETURN
      END
