      SUBROUTINE CLASSS(TBARROW,THLQROW,THICROW,TPNDROW,ZPNDROW,
     1                  TBASROW,ALBSROW,TSNOROW,RHOSROW,SNOROW, 
     2                  TCANROW,RCANROW,SCANROW,GROROW,TSFSROW, 
     3                  CDHROW, CDMROW, HFSROW, TFXROW, QEVPROW,
     4                  QFSROW, QFXROW, PETROW, GAROW,  EFROW,
     5                  GTROW,  QGROW,  TSFROW, ALVSROW,ALIRROW,
     6                  CMAIROW,SFCTROW,SFCUROW,SFCVROW,SFCQROW,
     7                  FSGVROW,FSGSROW,FSGGROW,FLGVROW,FLGSROW,
     8                  FLGGROW,HFSCROW,HFSSROW,HFSGROW,HEVCROW,
     9                  HEVSROW,HEVGROW,HMFCROW,HMFNROW,HTCCROW,
     A                  HTCSROW,PCFCROW,PCLCROW,PCPNROW,PCPGROW,
     B                  QFGROW, QFNROW, QFCLROW,QFCFROW,ROFROW,
     C                  ROFOROW,ROFSROW,ROFBROW,TROFROW,TROOROW,
     D                  TROSROW,TROBROW,ROFCROW,ROFNROW,ROVGROW,
     E                  WTRCROW,WTRSROW,WTRGROW,DRROW,  WTABROW,
     F                  ILMOROW,UEROW,  HBLROW, TACROW, QACROW,
     G                  HMFGROW,HTCROW, QFCROW, WSNOROW,FSNOROW,
     H                  GFLXROW,ITCTROW,ILMOS,JLMOS,IWMOS,JWMOS,
     I                  NML,NL,NM,ILG,IG,IC,ICP1,
     J                  TBARGAT,THLQGAT,THICGAT,TPNDGAT,ZPNDGAT,
     K                  TBASGAT,ALBSGAT,TSNOGAT,RHOSGAT,SNOGAT, 
     L                  TCANGAT,RCANGAT,SCANGAT,GROGAT,TSFSGAT, 
     M                  CDHGAT, CDMGAT, HFSGAT, TFXGAT, QEVPGAT,
     N                  QFSGAT, QFXGAT, PETGAT, GAGAT,  EFGAT,
     O                  GTGAT,  QGGAT,  TSFGAT, ALVSGAT,ALIRGAT,
     P                  CMAIGAT,SFCTGAT,SFCUGAT,SFCVGAT,SFCQGAT,
     Q                  FSGVGAT,FSGSGAT,FSGGGAT,FLGVGAT,FLGSGAT,
     R                  FLGGGAT,HFSCGAT,HFSSGAT,HFSGGAT,HEVCGAT,
     S                  HEVSGAT,HEVGGAT,HMFCGAT,HMFNGAT,HTCCGAT,
     T                  HTCSGAT,PCFCGAT,PCLCGAT,PCPNGAT,PCPGGAT,
     U                  QFGGAT, QFNGAT, QFCLGAT,QFCFGAT,ROFGAT,
     V                  ROFOGAT,ROFSGAT,ROFBGAT,TROFGAT,TROOGAT,
     W                  TROSGAT,TROBGAT,ROFCGAT,ROFNGAT,ROVGGAT,
     X                  WTRCGAT,WTRSGAT,WTRGGAT,DRGAT,  WTABGAT,
     Y                  ILMOGAT,UEGAT,  HBLGAT, TACGAT, QACGAT,
     Z                  HMFGGAT,HTCGAT, QFCGAT, WSNOGAT,FSNOGAT,
     +                  GFLXGAT,ITCTGAT)
C
C     * MAR 23/06 - D.VERSEGHY. ADD WSNO,FSNO.
C     * MAR 18/05 - D.VERSEGHY. ADDITIONAL VARIABLES.
C     * FEB 18/05 - D.VERSEGHY. ADD "TSFS" VARIABLES.
C     * AUG 05/04 - D.VERSEGHY. ADD NEW DIAGNOSTIC VARIABLES
C     *                         ILMO, UE AND HBL.
C     * AUG 15/02 - D.VERSEGHY. SCATTER OPERATION ON CLASS 
C     *                         VARIABLES.
C
      IMPLICIT NONE
C
C     * INTEGER CONSTANTS.
C
      INTEGER NML,NL,NM,ILG,IG,IC,ICP1,K,L,M
C
C     * LAND SURFACE PROGNOSTIC VARIABLES.
C
      REAL    TBARROW(NL,NM,IG), THLQROW(NL,NM,IG), THICROW(NL,NM,IG), 
     1        TPNDROW(NL,NM),    ZPNDROW(NL,NM),    TBASROW(NL,NM),   
     2        ALBSROW(NL,NM),    TSNOROW(NL,NM),    RHOSROW(NL,NM),   
     3        SNOROW (NL,NM),    TCANROW(NL,NM),    RCANROW(NL,NM),   
     4        SCANROW(NL,NM),    GROROW (NL,NM),    TSFSROW(NL,NM,4),
     5        TACROW (NL,NM),    QACROW (NL,NM),    WSNOROW(NL,NM)
C
      REAL    TBARGAT(ILG,IG),   THLQGAT(ILG,IG),   THICGAT(ILG,IG), 
     1        TPNDGAT(ILG),      ZPNDGAT(ILG),      TBASGAT(ILG),   
     2        ALBSGAT(ILG),      TSNOGAT(ILG),      RHOSGAT(ILG),   
     3        SNOGAT (ILG),      TCANGAT(ILG),      RCANGAT(ILG),   
     4        SCANGAT(ILG),      GROGAT (ILG),      TSFSGAT(ILG,4),
     5        TACGAT (ILG),      QACGAT (ILG),      WSNOGAT(ILG)
C
C     * GATHER-SCATTER INDEX ARRAYS.
C
      INTEGER  ILMOS (ILG),  JLMOS  (ILG),  IWMOS  (ILG),  JWMOS (ILG)
C
C     * LAND SURFACE DIAGNOSTIC VARIABLES.
C
      REAL  CDHROW (NL,NM),CDMROW (NL,NM),HFSROW (NL,NM),TFXROW (NL,NM),
     1      QEVPROW(NL,NM),QFSROW (NL,NM),QFXROW (NL,NM),PETROW (NL,NM),
     2      GAROW  (NL,NM),EFROW  (NL,NM),GTROW  (NL,NM),QGROW  (NL,NM), 
     3      TSFROW (NL,NM),ALVSROW(NL,NM),ALIRROW(NL,NM),CMAIROW(NL,NM), 
     4      SFCTROW(NL,NM),SFCUROW(NL,NM),SFCVROW(NL,NM),SFCQROW(NL,NM), 
     5      FSGVROW(NL,NM),FSGSROW(NL,NM),FSGGROW(NL,NM),FLGVROW(NL,NM), 
     6      FLGSROW(NL,NM),FLGGROW(NL,NM),HFSCROW(NL,NM),HFSSROW(NL,NM),
     7      HFSGROW(NL,NM),HEVCROW(NL,NM),HEVSROW(NL,NM),HEVGROW(NL,NM), 
     8      HMFCROW(NL,NM),HMFNROW(NL,NM),HTCCROW(NL,NM),HTCSROW(NL,NM), 
     9      PCFCROW(NL,NM),PCLCROW(NL,NM),PCPNROW(NL,NM),PCPGROW(NL,NM), 
     A      QFGROW (NL,NM),QFNROW (NL,NM),QFCLROW(NL,NM),QFCFROW(NL,NM), 
     B      ROFROW (NL,NM),ROFOROW(NL,NM),ROFSROW(NL,NM),ROFBROW(NL,NM),
     C      TROFROW(NL,NM),TROOROW(NL,NM),TROSROW(NL,NM),TROBROW(NL,NM),
     D      ROFCROW(NL,NM),ROFNROW(NL,NM),ROVGROW(NL,NM),WTRCROW(NL,NM), 
     E      WTRSROW(NL,NM),WTRGROW(NL,NM),DRROW  (NL,NM),WTABROW(NL,NM),
     F      ILMOROW(NL,NM),UEROW  (NL,NM),HBLROW (NL,NM),FSNOROW(NL,NM)
C
      REAL  CDHGAT (ILG),  CDMGAT (ILG),  HFSGAT (ILG),  TFXGAT (ILG),
     1      QEVPGAT(ILG),  QFSGAT (ILG),  QFXGAT (ILG),  PETGAT (ILG),
     2      GAGAT  (ILG),  EFGAT  (ILG),  GTGAT  (ILG),  QGGAT  (ILG), 
     3      TSFGAT (ILG),  ALVSGAT(ILG),  ALIRGAT(ILG),  CMAIGAT(ILG), 
     4      SFCTGAT(ILG),  SFCUGAT(ILG),  SFCVGAT(ILG),  SFCQGAT(ILG), 
     5      FSGVGAT(ILG),  FSGSGAT(ILG),  FSGGGAT(ILG),  FLGVGAT(ILG), 
     6      FLGSGAT(ILG),  FLGGGAT(ILG),  HFSCGAT(ILG),  HFSSGAT(ILG),
     7      HFSGGAT(ILG),  HEVCGAT(ILG),  HEVSGAT(ILG),  HEVGGAT(ILG), 
     8      HMFCGAT(ILG),  HMFNGAT(ILG),  HTCCGAT(ILG),  HTCSGAT(ILG), 
     9      PCFCGAT(ILG),  PCLCGAT(ILG),  PCPNGAT(ILG),  PCPGGAT(ILG), 
     A      QFGGAT (ILG),  QFNGAT (ILG),  QFCLGAT(ILG),  QFCFGAT(ILG), 
     B      ROFGAT (ILG),  ROFOGAT(ILG),  ROFSGAT(ILG),  ROFBGAT(ILG),
     C      TROFGAT(ILG),  TROOGAT(ILG),  TROSGAT(ILG),  TROBGAT(ILG),
     D      ROFCGAT(ILG),  ROFNGAT(ILG),  ROVGGAT(ILG),  WTRCGAT(ILG), 
     E      WTRSGAT(ILG),  WTRGGAT(ILG),  DRGAT  (ILG),  WTABGAT(ILG),
     F      ILMOGAT(ILG),  UEGAT  (ILG),  HBLGAT (ILG),  FSNOGAT(ILG)
C
      REAL    HMFGROW(NL,NM,IG),HTCROW (NL,NM,IG),QFCROW (NL,NM,IG),
     1        GFLXROW(NL,NM,IG),
     2        HMFGGAT(ILG,IG),  HTCGAT (ILG,IG),  QFCGAT (ILG,IG),
     3        GFLXGAT(ILG,IG)
C
      INTEGER        ITCTROW(NL,NM,6,50),    ITCTGAT(ILG,6,50)
C
C----------------------------------------------------------------------
      DO 100 K=1,NML
          TPNDROW(ILMOS(K),JLMOS(K))=TPNDGAT(K)  
          ZPNDROW(ILMOS(K),JLMOS(K))=ZPNDGAT(K)  
          TBASROW(ILMOS(K),JLMOS(K))=TBASGAT(K)  
          ALBSROW(ILMOS(K),JLMOS(K))=ALBSGAT(K)  
          TSNOROW(ILMOS(K),JLMOS(K))=TSNOGAT(K)  
          RHOSROW(ILMOS(K),JLMOS(K))=RHOSGAT(K)  
          SNOROW (ILMOS(K),JLMOS(K))=SNOGAT (K)  
          WSNOROW(ILMOS(K),JLMOS(K))=WSNOGAT(K)  
          TCANROW(ILMOS(K),JLMOS(K))=TCANGAT(K)  
          RCANROW(ILMOS(K),JLMOS(K))=RCANGAT(K)  
          SCANROW(ILMOS(K),JLMOS(K))=SCANGAT(K)  
          GROROW (ILMOS(K),JLMOS(K))=GROGAT (K)  
          TACROW (ILMOS(K),JLMOS(K))=TACGAT (K)  
          QACROW (ILMOS(K),JLMOS(K))=QACGAT (K)  
          CDHROW (ILMOS(K),JLMOS(K))=CDHGAT (K)  
          CDMROW (ILMOS(K),JLMOS(K))=CDMGAT (K)  
          HFSROW (ILMOS(K),JLMOS(K))=HFSGAT (K)  
          TFXROW (ILMOS(K),JLMOS(K))=TFXGAT (K)  
          QEVPROW(ILMOS(K),JLMOS(K))=QEVPGAT(K)  
          QFSROW (ILMOS(K),JLMOS(K))=QFSGAT (K)  
          QFXROW (ILMOS(K),JLMOS(K))=QFXGAT (K)  
          PETROW (ILMOS(K),JLMOS(K))=PETGAT (K)  
          GAROW  (ILMOS(K),JLMOS(K))=GAGAT  (K)  
          EFROW  (ILMOS(K),JLMOS(K))=EFGAT  (K)  
          GTROW  (ILMOS(K),JLMOS(K))=GTGAT  (K)  
          QGROW  (ILMOS(K),JLMOS(K))=QGGAT  (K)  
          TSFROW (ILMOS(K),JLMOS(K))=TSFGAT (K)  
          ALVSROW(ILMOS(K),JLMOS(K))=ALVSGAT(K)  
          ALIRROW(ILMOS(K),JLMOS(K))=ALIRGAT(K)  
          CMAIROW(ILMOS(K),JLMOS(K))=CMAIGAT(K)  
          SFCTROW(ILMOS(K),JLMOS(K))=SFCTGAT(K)  
          SFCUROW(ILMOS(K),JLMOS(K))=SFCUGAT(K)  
          SFCVROW(ILMOS(K),JLMOS(K))=SFCVGAT(K)  
          SFCQROW(ILMOS(K),JLMOS(K))=SFCQGAT(K)  
          FSNOROW(ILMOS(K),JLMOS(K))=FSNOGAT(K)  
          FSGVROW(ILMOS(K),JLMOS(K))=FSGVGAT(K)  
          FSGSROW(ILMOS(K),JLMOS(K))=FSGSGAT(K)  
          FSGGROW(ILMOS(K),JLMOS(K))=FSGGGAT(K)  
          FLGVROW(ILMOS(K),JLMOS(K))=FLGVGAT(K)  
          FLGSROW(ILMOS(K),JLMOS(K))=FLGSGAT(K)  
          FLGGROW(ILMOS(K),JLMOS(K))=FLGGGAT(K)  
          HFSCROW(ILMOS(K),JLMOS(K))=HFSCGAT(K)  
          HFSSROW(ILMOS(K),JLMOS(K))=HFSSGAT(K)  
          HFSGROW(ILMOS(K),JLMOS(K))=HFSGGAT(K)  
          HEVCROW(ILMOS(K),JLMOS(K))=HEVCGAT(K)  
          HEVSROW(ILMOS(K),JLMOS(K))=HEVSGAT(K)  
          HEVGROW(ILMOS(K),JLMOS(K))=HEVGGAT(K)  
          HMFCROW(ILMOS(K),JLMOS(K))=HMFCGAT(K)  
          HMFNROW(ILMOS(K),JLMOS(K))=HMFNGAT(K)  
          HTCCROW(ILMOS(K),JLMOS(K))=HTCCGAT(K)  
          HTCSROW(ILMOS(K),JLMOS(K))=HTCSGAT(K)  
          PCFCROW(ILMOS(K),JLMOS(K))=PCFCGAT(K)  
          PCLCROW(ILMOS(K),JLMOS(K))=PCLCGAT(K)  
          PCPNROW(ILMOS(K),JLMOS(K))=PCPNGAT(K)  
          PCPGROW(ILMOS(K),JLMOS(K))=PCPGGAT(K)  
          QFGROW (ILMOS(K),JLMOS(K))=QFGGAT (K)  
          QFNROW (ILMOS(K),JLMOS(K))=QFNGAT (K)  
          QFCLROW(ILMOS(K),JLMOS(K))=QFCLGAT(K)  
          QFCFROW(ILMOS(K),JLMOS(K))=QFCFGAT(K)  
          ROFROW (ILMOS(K),JLMOS(K))=ROFGAT (K)  
          ROFOROW(ILMOS(K),JLMOS(K))=ROFOGAT(K)  
          ROFSROW(ILMOS(K),JLMOS(K))=ROFSGAT(K)  
          ROFBROW(ILMOS(K),JLMOS(K))=ROFBGAT(K)  
          TROFROW(ILMOS(K),JLMOS(K))=TROFGAT(K)  
          TROOROW(ILMOS(K),JLMOS(K))=TROOGAT(K)  
          TROSROW(ILMOS(K),JLMOS(K))=TROSGAT(K)  
          TROBROW(ILMOS(K),JLMOS(K))=TROBGAT(K)  
          ROFCROW(ILMOS(K),JLMOS(K))=ROFCGAT(K)  
          ROFNROW(ILMOS(K),JLMOS(K))=ROFNGAT(K)  
          ROVGROW(ILMOS(K),JLMOS(K))=ROVGGAT(K)  
          WTRCROW(ILMOS(K),JLMOS(K))=WTRCGAT(K)  
          WTRSROW(ILMOS(K),JLMOS(K))=WTRSGAT(K)  
          WTRGROW(ILMOS(K),JLMOS(K))=WTRGGAT(K)  
          DRROW  (ILMOS(K),JLMOS(K))=DRGAT  (K)  
          WTABROW(ILMOS(K),JLMOS(K))=WTABGAT(K)  
          ILMOROW(ILMOS(K),JLMOS(K))=ILMOGAT(K)  
          UEROW  (ILMOS(K),JLMOS(K))=UEGAT(K)  
          HBLROW (ILMOS(K),JLMOS(K))=HBLGAT(K)  
100   CONTINUE
C
      DO 200 L=1,IG
      DO 200 K=1,NML
          TBARROW(ILMOS(K),JLMOS(K),L)=TBARGAT(K,L)
          THLQROW(ILMOS(K),JLMOS(K),L)=THLQGAT(K,L)
          THICROW(ILMOS(K),JLMOS(K),L)=THICGAT(K,L)
          HMFGROW(ILMOS(K),JLMOS(K),L)=HMFGGAT(K,L)
          HTCROW (ILMOS(K),JLMOS(K),L)=HTCGAT (K,L)
          QFCROW (ILMOS(K),JLMOS(K),L)=QFCGAT (K,L)
          GFLXROW(ILMOS(K),JLMOS(K),L)=GFLXGAT(K,L)
200   CONTINUE
C
      DO 300 L=1,4
      DO 300 K=1,NML
          TSFSROW(ILMOS(K),JLMOS(K),L)=TSFSGAT(K,L)
300   CONTINUE
C
      DO 500 M=1,50
          DO 475 L=1,6
              DO 450 K=1,NML
                  ITCTROW(ILMOS(K),JLMOS(K),L,M)=ITCTGAT(K,L,M)
450           CONTINUE
475       CONTINUE
500   CONTINUE
C
      RETURN
      END
