SUBROUTINE GATHER(NA,NML,ILG,ILMOS,GRD,GAT)

!SIMPLE VERSION OF THE CLASSG SUBROUTINE.
    
    INTEGER NA,NML,ILG
    INTEGER ILMOS(ILG)
    REAL    GRD(NA),GAT(ILG)
    
    INTEGER K
    
    DO K = 1,NML
       GAT(K) = GRD(ILMOS(K))
   enddo

END SUBROUTINE
