# ======================================================================
# Include or header file for SA_MESH makefile

# ======================================================================
# Directory of source code

# Update the DIR_REPO variable as appropriate.
#
# Current directory (default): DIR_REPO=.
# Cygwin: DIR_REPO=/cygdrive/c/sample_path
# MinGW on Windows: C:\sample_path
# Linux: DIR_REPO=/home/sample_path

DIR_REPO=.

# Defaults.
VPATH=
INC_DIRS=
OBJECTS=

# ======================================================================
# JAMS-CHS.
# Paths.
ifeq ($(NC),yes)
VPATH+=	$(DIR_REPO)/Modules/jams_chs:
# Core routines.
OBJECTS+=	mo_kind.o mo_julian.o mo_netcdf.o
endif

# ======================================================================
# Primitives for SA_MESH.
# Paths.
VPATH+=	$(DIR_REPO)/Driver/MESH_Driver: \
		$(DIR_REPO)/Modules/strings: \
		$(DIR_REPO)/Modules/mpi_module: \
		$(DIR_REPO)/Modules/climate_forcing_module: \
		$(DIR_REPO)/Modules/simulation_statistics: \
		$(DIR_REPO)/Modules/cropland_irrigation: \
		$(DIR_REPO)/Modules/permafrost_outputs: \
		$(DIR_REPO)/Blowing_Snow: \
		$(DIR_REPO)/Routing_Model/baseflow_module: \
		$(DIR_REPO)/Modules/io_modules:
# MPI modules.
OBJECTS+=	mpi_flags.o mpi_shared_variables.o mpi_utilities.o \
			mpi_module.o
# String parsing primitives.
OBJECTS+=	precmod.o stringmod.o
# I/O primitives.
OBJECTS+=	print_routines.o program_end.o program_abort.o \
			txt_io.o ensim_io.o
# Variables (common).
OBJECTS+=	module_files_variabletypes.o module_files_variables.o \
			module_dates.o \
			EF_Module.o EF_ParseUtilities.o FLAGS.o \
			parse_utilities.o \
			climate_forcing_module_constants.o climate_forcing_module_variabletypes.o \
			control_variables.o \
			variable_names.o parameter_names.o \
			shd_variables.o fm_variables.o input_parameters.o model_variables.o \
			climate_forcing_module_config.o \
			climate_forcing_module_io.o climate_forcing_module.o \
			output_variables.o \
			sa_mesh_common.o \
			read_init_prog_variables_class.o save_init_prog_variables_class.o \
			tile_connector.o
# Process modules.
OBJECTS+=	baseFlow_luo2012.o baseflow_wfqlz.o baseflow_module.o
OBJECTS+=	permafrost_ald.o permafrost_zod.o permafrost_outputs_module.o
OBJECTS+=	cropland_irrigation_variables.o \
			cropland_irrigation_init.o \
			cropland_irrigation_within_tile.o cropland_irrigation_between_grid.o \
			calc_ET0.o
OBJECTS+=	SIMSTATS_config.o \
			NSE.o SAE.o SORT.o SAESRT.o calc_drms.o calc_abserr.o \
			SIMSTATS.o
#todo: fix dependency on RUNCLASS36_constants;
OBJECTS+=	RUNCLASS36_constants.o
OBJECTS+=	PBSMrates.o PBSMrun.o ProbabilityThreshold.o REDISTRIB_SNOW.o SUM.o \
			PBSM_module.o

# ======================================================================
# CLASS (3.6).
# Paths.
VPATH+=	$(DIR_REPO)/LSS_Model/CLASS/3.6/sa_mesh_process: \
		$(DIR_REPO)/LSS_Model/CLASS/3.6/src:
# Core routines.
OBJECTS+=	CLASSBD.o CLASSD.o CLASSBG.o CLASSI.o \
			APREP.o SNOALBA.o GRALB.o CANALB.o \
			CLASSA.o \
			DRCOEF.o FLXSURFZ.o SLDIAG.o DIASURFZ.o \
			SCREENRH.o \
			TPREP.o CWCALC.o TNPREP.o TSPREP.o TSOLVC.o TSOLVE.o \
			TSPOST.o TNPOST.o CLASST.o \
			WPREP.o CANVAP.o CANADD.o SUBCAN.o TWCALC.o \
			SNOVAP.o TFREEZ.o TMELT.o SNOADD.o SNINFL.o \
			FROZEN.o SNINFLM.o \
			ICEBAL.o \
			GRINFL.o WFILL.o WFLOW.o WEND.o GRDRAN.o \
			WATDRN.o WATROF.o LATFLOW.o PDMROF.o \
			TMCALC.o CHKWAT.o SNOALBW.o CGROW.o CLASSW.o \
			XIT.o CLASSZ.o
# SA_MESH modules.
OBJECTS+=	RUNCLASS36_variables.o RUNCLASS36_save_output.o \
			RUNCLASS36_config.o RUNCLASS36_module.o

# ======================================================================
# SVS (531).
# Paths.
PHY=$(DIR_REPO)/LSS_Model/SVS/r531/rpnphy_5.5.0-rc2_all
CHANGES2PHY=$(DIR_REPO)/LSS_Model/SVS/r531/changes_to_rpnphy
SVS=$(DIR_REPO)/LSS_Model/SVS/r531/svs_v1.1.3_cleanup_mesh
VPATH+=	$(DIR_REPO)/LSS_Model/SVS/r531/sa_mesh_process: \
		$(PHY): $(CHANGES2PHY): $(SVS) \
		$(DIR_REPO)/LSS_Model/SVS/r531/rmnlib_013: \
		$(DIR_REPO)/LSS_Model/SVS/r531/src:
# Includes.
INC_DIRS+=-I$(CHANGES2PHY) -I$(PHY) -I$(SVS)
# Variables.
DFLAG=-DRUNSVS
# Core routines.
OBJECTS+=	datec.o moduledate.o \
			runsvs_mod_sa_mesh.o runsvs_utils.o runsvs_io_mesh.o \
			runsvs_init_mesh.o \
			inicover_svs.o inisoili_svs.o \
			svs.o soili_svs.o \
			aggveghigh.o aggveglow.o veglowhigh.o vegi_svs.o drag_svs.o \
			snow_alone.o snow_veg.o ebudget_svs.o \
			RUNSVSDRN.o \
			hydro_svs.o phtsyn_svs.o update_svs.o \
			phy_debu_data.o \
			vscos.o vssin.o vslog.o \
			aggcovernat.o juliand.o suncos1.o prelim1.o interpveg.o flxsurf.o \
			compz0.o sf_heat.o sf_momentum.o sf_pblheight.o diasurf2.o \
			phyopt_initdata.o
# SA_MESH modules.
OBJECTS+=	RUNSVS113_variables.o \
			RUNSVS113_config.o RUNSVS113_module.o

# ======================================================================
# WF_ROUTE and SA_RTE.
# Paths.
VPATH+=	$(DIR_REPO)/Routing_Model/WatRoute_old: \
		$(DIR_REPO)/Routing_Model/RPN_watroute/sa_mesh_process:
# Files.
OBJECTS+=	WF_ROUTE_config.o WF_ROUTE.o WF_ROUTE_module.o
OBJECTS+=	SA_RTE_module.o

# ======================================================================
# RTE.
# Paths.
VPATH+=	$(DIR_REPO)/Routing_Model/RPN_watroute/sa_mesh_process: \
		$(DIR_REPO)/Routing_Model/RPN_watroute/code:
# Files.
OBJECTS+=	area_watflood.o rerout.o route.o flowinit.o \
			rte_module.o

# ======================================================================
# SA_MESH routines.
# Input routines.
OBJECTS+=	read_initial_inputs.o \
			read_shed_r2c.o read_soil_levels.o \
			read_parameters.o \
			read_parameters_class.o read_parameters_hydrology.o read_parameters_r2c.o read_parameters_csv.o \
			check_parameters.o \
			read_basin_structures.o \
			read_streamflow_txt.o read_streamflow_tb0.o read_reservoir_txt.o read_reservoir_tb0.o \
			read_soil_ini.o \
			read_initial_states.o \
			module_files.o
# Output routines.
OBJECTS+=	WRITE_R2C_HEADER.o write_r2c.o \
			output_files.o save_basin_output.o
# MESH driver.
OBJECTS+=	read_run_options.o \
			sa_mesh_run_within_tile.o sa_mesh_run_within_grid.o sa_mesh_run_between_grid.o \
			MESH_driver.o
