      PROGRAM RUNCLASS

C     * SHELL PROGRAM TO RUN "CLASS" ("CANADIAN LAND SURFACE SCHEME")
C     * VERSION 3.6 IN STAND-ALONE MODE USING SPECIFIED BOUNDARY 
C     * CONDITIONS AND ATMOSPHERIC FORCING.

C=======================================================================
C     * DIMENSION STATEMENTS.

C     * FIRST SET OF DEFINITIONS:
C     * BACKGROUND VARIABLES, AND PROGNOSTIC AND DIAGNOSTIC
C     * VARIABLES NORMALLY PROVIDED BY AND/OR USED BY THE GCM.
C     * THE SUFFIX "ROT" REFERS TO VARIABLES EXISTING ON THE 
C     * MOSAIC GRID ON THE CURRENT LATITUDE CIRCLE.  THE SUFFIX 
C     * "GAT" REFERS TO THE SAME VARIABLES AFTER THEY HAVE UNDERGONE
C     * A "GATHER" OPERATION IN WHICH THE TWO MOSAIC DIMENSIONS
C     * ARE COLLAPSED INTO ONE.  THE SUFFIX "ROW" REFERS BOTH TO 
C     * GRID-CONSTANT INPUT VARIABLES. AND TO GRID-AVERAGED
C     * DIAGNOSTIC VARIABLES.
C     
C     * THE FIRST DIMENSION ELEMENT OF THE "ROT" VARIABLES 
C     * REFERS TO THE NUMBER OF GRID CELLS ON THE CURRENT 
C     * LATITUDE CIRCLE.  IN THIS STAND-ALONE VERSION, THIS 
C     * NUMBER IS ARBITRARILY SET TO THREE, TO ALLOW UP TO THREE
C     * SIMULTANEOUS TESTS TO BE RUN.  THE SECOND DIMENSION 
C     * ELEMENT OF THE "ROT" VARIABLES REFERS TO THE MAXIMUM
C     * NUMBER OF TILES IN THE MOSAIC.  IN THIS STAND-ALONE
C     * VERSION, THIS NUMBER IS SET TO EIGHT.  THE FIRST 
C     * DIMENSION ELEMENT IN THE "GAT" VARIABLES IS GIVEN BY
C     * THE PRODUCT OF THE FIRST TWO DIMENSION ELEMENTS IN THE
C     * "ROT" VARIABLES.
C
      IMPLICIT NONE
C
C     * INTEGER CONSTANTS.
C
      INTEGER,PARAMETER :: NLAT=3,NMOS=8,ILG=NLAT*NMOS
      INTEGER,PARAMETER :: ICAN=4,IGND=3,ICP1=ICAN+1,ICTEM=1
C      INTEGER,PARAMETER :: ICAN=4,IGND=9,ICP1=ICAN+1
C
      INTEGER IDISP,IZREF,ISLFD,IPCP,IWF,IPAI,IHGT,IALC,
     1        IALS,IALG,N,ITG,ITC,ITCG,NLTEST,NMTEST,
     2        NCOUNT,NDAY,IHOUR,IMIN,IDAY,IYEAR,NML,NMW,JLAT,
     3        NLANDCS,NLANDGS,NLANDC,NLANDG,NLANDI,I,J,K,L,M
C
      INTEGER K1,K2,K3,K4,K5,K6,K7,K8,K9,K10,K11
C
C     * LAND SURFACE PROGNOSTIC VARIABLES.
C
      REAL,DIMENSION(NLAT,NMOS,IGND) ::
     1        TBARROT,   THLQROT,   THICROT
C
      REAL,DIMENSION(NLAT,NMOS) ::
     1        TPNDROT,   ZPNDROT,   TBASROT,   
     2        ALBSROT,   TSNOROT,   RHOSROT,   
     3        SNOROT ,   TCANROT,   RCANROT,   
     4        SCANROT,   GROROT ,   CMAIROT,
     5        TACROT ,   QACROT ,   WSNOROT
C
      REAL    TSFSROT(NLAT,NMOS,4)
C
      REAL,DIMENSION(ILG,IGND) ::
     1        TBARGAT, THLQGAT, THICGAT 
C
      REAL,DIMENSION(ILG) ::
     1        TPNDGAT,   ZPNDGAT,   TBASGAT,   
     2        ALBSGAT,   TSNOGAT,   RHOSGAT,   
     3        SNOGAT ,   TCANGAT,   RCANGAT,   
     4        SCANGAT,   GROGAT ,   CMAIGAT,
     5        TACGAT ,   QACGAT ,   WSNOGAT
C
      REAL    TSFSGAT(ILG,4)
C
C     * GATHER-SCATTER INDEX ARRAYS.
C
      INTEGER  ILMOS (ILG),  JLMOS  (ILG),  IWMOS  (ILG),  JWMOS (ILG)
C
C     * CANOPY AND SOIL INFORMATION ARRAYS.
C     * (THE LAST DIMENSION OF MOST OF THESE ARRAYS IS GIVEN BY
C     * THE NUMBER OF SOIL LAYERS (IGND), THE NUMBER OF BROAD 
C     * VEGETATION CATEGORIES (ICAN), OR ICAN+1.
C
      REAL,DIMENSION(NLAT,NMOS,ICP1) ::
     1              FCANROT,  LNZ0ROT,
     2              ALVCROT,  ALICROT
C
      REAL,DIMENSION(NLAT,NMOS,ICAN) ::
     1              PAMXROT,  PAMNROT,
     2              CMASROT,  ROOTROT,
     3              RSMNROT,  QA50ROT,
     4              VPDAROT,  VPDBROT,
     5              PSGAROT,  PSGBROT,
     6              PAIDROT,  HGTDROT,
     7              ACVDROT,  ACIDROT
C
      REAL,DIMENSION(ILG,ICP1) ::
     1              FCANGAT,  LNZ0GAT,
     2              ALVCGAT,  ALICGAT
C
      REAL,DIMENSION(ILG,ICAN) ::
     1              PAMXGAT,  PAMNGAT,
     2              CMASGAT,  ROOTGAT,
     3              RSMNGAT,  QA50GAT,
     4              VPDAGAT,  VPDBGAT,
     5              PSGAGAT,  PSGBGAT,
     6              PAIDGAT,  HGTDGAT,
     7              ACVDGAT,  ACIDGAT
C
      REAL,DIMENSION(NLAT,NMOS,IGND) ::
     1        THPROT ,  THRROT ,  THMROT , 
     2        BIROT  ,  PSISROT,  GRKSROT,    
     3        THRAROT,  HCPSROT,  
     4        TCSROT ,  THFCROT,  PSIWROT,   
     5        DLZWROT,  ZBTWROT 
C
      REAL,DIMENSION(NLAT,NMOS) ::
     1        DRNROT ,   XSLPROT,   GRKFROT,
     2        WFSFROT,   WFCIROT,   ALGWROT,   
     3        ALGDROT,   ASVDROT,   ASIDROT,   
     4        AGVDROT,   AGIDROT,   ZSNLROT,
     5        ZPLGROT,   ZPLSROT
C
      REAL,DIMENSION(ILG,IGND) ::
     1        THPGAT ,  THRGAT ,  THMGAT , 
     2        BIGAT  ,  PSISGAT,  GRKSGAT,    
     3        THRAGAT,  HCPSGAT,  
     4        TCSGAT ,  THFCGAT,  PSIWGAT,   
     5        DLZWGAT,  ZBTWGAT
C
      REAL,DIMENSION(ILG) ::
     1        DRNGAT ,   XSLPGAT,   GRKFGAT,
     2        WFSFGAT,   WFCIGAT,   ALGWGAT,     
     3        ALGDGAT,   ASVDGAT,   ASIDGAT,     
     4        AGVDGAT,   AGIDGAT,   ZSNLGAT,
     5        ZPLGGAT,   ZPLSGAT
C
      REAL    SANDROT(NLAT,NMOS,IGND), CLAYROT(NLAT,NMOS,IGND), 
     1        ORGMROT(NLAT,NMOS,IGND),
     2        SDEPROT(NLAT,NMOS),      FAREROT(NLAT,NMOS)
C
      INTEGER MIDROT (NLAT,NMOS),     ISNDROT(NLAT,NMOS,IGND), 
     1        ISNDGAT( ILG,IGND),     IGDRROT(NLAT,NMOS),
     2        IGDRGAT( ILG)
C
C     * ARRAYS ASSOCIATED WITH COMMON BLOCKS.
C
      REAL  THPORG (  3), THRORG (  3), THMORG (  3), BORG   (  3),
     1      PSISORG(  3), GRKSORG(  3)
C
      REAL  CANEXT(ICAN), XLEAF (ICAN), ZORAT (ICAN),
     1      DELZ  (IGND), ZBOT  (IGND), 
     2      GROWYR (  18,4,2)
C
C     * ATMOSPHERIC AND GRID-CONSTANT INPUT VARIABLES.
C
      REAL,DIMENSION(NLAT) ::
     1      ZRFMROW,   ZRFHROW,   ZDMROW ,   ZDHROW ,  
     2      ZBLDROW,   FSVHROW,   FSIHROW,   RADJROW,
     3      CSZROW ,   FDLROW ,   ULROW  ,   VLROW  ,   
     4      TAROW  ,   QAROW  ,   PRESROW,   PREROW ,  
     5      PADRROW,   VPDROW ,   TADPROW,   RHOAROW,  
     6      RPCPROW,   TRPCROW,   SPCPROW,   TSPCROW,  
     7      RHSIROW,   FCLOROW,   DLONROW,   UVROW  ,   
     8      XDIFFUS,   GCROW  ,   Z0ORROW,   GGEOROW,
     9      RPREROW,   SPREROW,   VMODROW
C
      REAL,DIMENSION(ILG) ::
     1      ZRFMGAT,   ZRFHGAT,   ZDMGAT ,   ZDHGAT ,  
     2      ZBLDGAT,   FSVHGAT,   FSIHGAT,   RADJGAT,
     3      CSZGAT ,   FDLGAT ,   ULGAT  ,   VLGAT  ,   
     4      TAGAT  ,   QAGAT  ,   PRESGAT,   PREGAT ,  
     5      PADRGAT,   VPDGAT ,   TADPGAT,   RHOAGAT,  
     6      RPCPGAT,   TRPCGAT,   SPCPGAT,   TSPCGAT,  
     7      RHSIGAT,   FCLOGAT,   DLONGAT,   Z0ORGAT,
     8      GGEOGAT,   VMODGAT
C
C     * LAND SURFACE DIAGNOSTIC VARIABLES.
C
      REAL,DIMENSION(NLAT,NMOS) ::
     1      CDHROT ,   CDMROT ,   HFSROT ,   TFXROT ,  
     2      QEVPROT,   QFSROT ,   QFXROT ,   PETROT ,  
     3      GAROT  ,   EFROT  ,   GTROT  ,   QGROT  ,   
     4      ALVSROT,   ALIRROT,   FSNOROT,   SFRHROT,
     5      SFCTROT,   SFCUROT,   SFCVROT,   SFCQROT,   
     6      FSGVROT,   FSGSROT,   FSGGROT,   FLGVROT,   
     7      FLGSROT,   FLGGROT,   HFSCROT,   HFSSROT,  
     8      HFSGROT,   HEVCROT,   HEVSROT,   HEVGROT,   
     9      HMFCROT,   HMFNROT,   HTCCROT,   HTCSROT,   
     A      PCFCROT,   PCLCROT,   PCPNROT,   PCPGROT,   
     B      QFGROT ,   QFNROT ,   QFCLROT,   QFCFROT,   
     C      ROFROT ,   ROFOROT,   ROFSROT,   ROFBROT,  
     D      TROFROT,   TROOROT,   TROSROT,   TROBROT,  
     E      ROFCROT,   ROFNROT,   ROVGROT,   WTRCROT,   
     F      WTRSROT,   WTRGROT,   DRROT  ,   WTABROT,  
     G      ILMOROT,   UEROT  ,   HBLROT 
C
      REAL,DIMENSION(ILG) ::
     1      CDHGAT ,   CDMGAT ,   HFSGAT ,   TFXGAT ,  
     2      QEVPGAT,   QFSGAT ,   QFXGAT ,   PETGAT ,  
     3      GAGAT  ,   EFGAT  ,   GTGAT  ,   QGGAT  ,   
     4      ALVSGAT,   ALIRGAT,   FSNOGAT,   SFRHGAT,
     5      SFCTGAT,   SFCUGAT,   SFCVGAT,   SFCQGAT,   
     6      FSGVGAT,   FSGSGAT,   FSGGGAT,   FLGVGAT,   
     7      FLGSGAT,   FLGGGAT,   HFSCGAT,   HFSSGAT,  
     8      HFSGGAT,   HEVCGAT,   HEVSGAT,   HEVGGAT,   
     9      HMFCGAT,   HMFNGAT,   HTCCGAT,   HTCSGAT,   
     A      PCFCGAT,   PCLCGAT,   PCPNGAT,   PCPGGAT,   
     B      QFGGAT ,   QFNGAT ,   QFCLGAT,   QFCFGAT,   
     C      ROFGAT ,   ROFOGAT,   ROFSGAT,   ROFBGAT,  
     D      TROFGAT,   TROOGAT,   TROSGAT,   TROBGAT,  
     E      ROFCGAT,   ROFNGAT,   ROVGGAT,   WTRCGAT,   
     F      WTRSGAT,   WTRGGAT,   DRGAT  ,   WTABGAT,  
     G      ILMOGAT,   UEGAT  ,   HBLGAT ,   QLWOGAT,
     H      FTEMP,     FVAP,      RIB
C
      REAL,DIMENSION(NLAT) ::
     1      CDHROW ,   CDMROW ,   HFSROW ,   TFXROW ,  
     2      QEVPROW,   QFSROW ,   QFXROW ,   PETROW ,  
     3      GAROW  ,   EFROW  ,   GTROW  ,   QGROW  ,   
     4      ALVSROW,   ALIRROW,   FSNOROW,   SFRHROW,
     5      SFCTROW,   SFCUROW,   SFCVROW,   SFCQROW,   
     6      FSGVROW,   FSGSROW,   FSGGROW,   FLGVROW,   
     7      FLGSROW,   FLGGROW,   HFSCROW,   HFSSROW,  
     8      HFSGROW,   HEVCROW,   HEVSROW,   HEVGROW,   
     9      HMFCROW,   HMFNROW,   HTCCROW,   HTCSROW,   
     A      PCFCROW,   PCLCROW,   PCPNROW,   PCPGROW,   
     B      QFGROW ,   QFNROW ,   QFCLROW,   QFCFROW,   
     C      ROFROW ,   ROFOROW,   ROFSROW,   ROFBROW,  
     D      ROFCROW,   ROFNROW,   ROVGROW,   WTRCROW,   
     E      WTRSROW,   WTRGROW,   DRROW  ,   WTABROW,  
     F      ILMOROW,   UEROW  ,   HBLROW 
C
      REAL    HMFGROT(NLAT,NMOS,IGND),   HTCROT (NLAT,NMOS,IGND),
     1        QFCROT (NLAT,NMOS,IGND),   GFLXROT(NLAT,NMOS,IGND),
     2        HMFGGAT(ILG,IGND),         HTCGAT (ILG,IGND), 
     3        QFCGAT (ILG,IGND),         GFLXGAT(ILG,IGND),
     4        HMFGROW(NLAT,IGND),        HTCROW (NLAT,IGND),
     5        QFCROW (NLAT,IGND),        GFLXROW(NLAT,IGND)
C
      INTEGER     ITCTROT(NLAT,NMOS,6,50),  ITCTGAT(ILG,6,50)
      INTEGER     ISUM(6)
 
C     * ARRAYS USED FOR OUTPUT AND DISPLAY PURPOSES.
C     * (THE SUFFIX "ACC" REFERS TO ACCUMULATOR ARRAYS USED IN
C     * CALCULATING TIME AVERAGES.)

      CHARACTER     TITLE1*4,     TITLE2*4,     TITLE3*4,
     1              TITLE4*4,     TITLE5*4,     TITLE6*4
      CHARACTER     NAME1*4,      NAME2*4,      NAME3*4,
     1              NAME4*4,      NAME5*4,      NAME6*4
      CHARACTER     PLACE1*4,     PLACE2*4,     PLACE3*4,
     1              PLACE4*4,     PLACE5*4,     PLACE6*4

      REAL,DIMENSION(NLAT) ::
     1              PREACC ,   GTACC  ,   QEVPACC,  
     2              HFSACC ,   ROFACC ,   SNOACC ,  
     3              ALVSACC,   ALIRACC,   FSINACC,  
     4              FLINACC,   TAACC  ,   UVACC  ,  
     5              PRESACC,   QAACC  ,  
     6              EVAPACC,   FLUTACC,   OVRACC ,  
     7              HMFNACC,   WTBLACC,   WSNOACC,  
     8              RHOSACC,   TSNOACC,   TCANACC,  
     9              RCANACC,   SCANACC,   GROACC ,  
     A              CANARE ,   SNOARE 

      REAL          TBARACC(NLAT,IGND), THLQACC(NLAT,IGND),
     1              THICACC(NLAT,IGND), THALACC(NLAT,IGND)
C 
C     * ARRAYS DEFINED TO PASS INFORMATION BETWEEN THE THREE MAJOR
C     * SUBSECTIONS OF CLASS ("CLASSA", "CLASST" AND "CLASSW").

      REAL,DIMENSION(ILG,IGND) ::
     1        TBARC  ,     TBARG  ,     TBARCS ,  
     2        TBARGS ,     THLIQC ,     THLIQG ,  
     3        THICEC ,     THICEG ,     FROOT  ,   
     4        HCPC   ,     HCPG   ,  
     5        TCTOPC ,     TCBOTC ,
     6        TCTOPG ,     TCBOTG
C
      REAL  FC     (ILG), FG     (ILG), FCS    (ILG), FGS    (ILG), 
     1      RBCOEF (ILG), ZSNOW  (ILG),
     2      FSVF   (ILG), FSVFS  (ILG),
     3      ALVSCN (ILG), ALIRCN (ILG), ALVSG  (ILG), ALIRG  (ILG),
     4      ALVSCS (ILG), ALIRCS (ILG), ALVSSN (ILG), ALIRSN (ILG),
     5      ALVSGC (ILG), ALIRGC (ILG), ALVSSC (ILG), ALIRSC (ILG), 
     6      TRVSCN (ILG), TRIRCN (ILG), TRVSCS (ILG), TRIRCS (ILG),
     7      RC     (ILG), RCS    (ILG), FRAINC (ILG), FSNOWC (ILG),
     8      FRAICS (ILG), FSNOCS (ILG),
     9      CMASSC (ILG), CMASCS (ILG), DISP   (ILG), DISPS  (ILG),
     A      ZOMLNC (ILG), ZOELNC (ILG), ZOMLNG (ILG), ZOELNG (ILG),
     B      ZOMLCS (ILG), ZOELCS (ILG), ZOMLNS (ILG), ZOELNS (ILG),
     C      TRSNOW (ILG), CHCAP  (ILG), CHCAPS (ILG),
     D      GZEROC (ILG), GZEROG (ILG), GZROCS (ILG), GZROGS (ILG),
     E      G12C   (ILG), G12G   (ILG), G12CS  (ILG), G12GS  (ILG),
     F      G23C   (ILG), G23G   (ILG), G23CS  (ILG), G23GS  (ILG),
     G      QFREZC (ILG), QFREZG (ILG), QMELTC (ILG), QMELTG (ILG),
     I      EVAPC  (ILG), EVAPCG (ILG), EVAPG  (ILG), EVAPCS (ILG),
     J      EVPCSG (ILG), EVAPGS (ILG), TCANO  (ILG), TCANS  (ILG),
     K      RAICAN (ILG), SNOCAN (ILG), RAICNS (ILG), SNOCNS (ILG),
     L      CWLCAP (ILG), CWFCAP (ILG), CWLCPS (ILG), CWFCPS (ILG),
     M      TSNOCS (ILG), TSNOGS (ILG), RHOSCS (ILG), RHOSGS (ILG),
     N      WSNOCS (ILG), WSNOGS (ILG),
     O      TPONDC (ILG), TPONDG (ILG), TPNDCS (ILG), TPNDGS (ILG),
     P      ZPLMCS (ILG), ZPLMGS (ILG), ZPLIMC (ILG), ZPLIMG (ILG)
C
C     * DIAGNOSTIC ARRAYS USED FOR CHECKING ENERGY AND WATER 
C     * BALANCES.
C
      REAL CTVSTP(ILG),   CTSSTP(ILG),   CT1STP(ILG),   CT2STP(ILG),
     1     CT3STP(ILG),   WTVSTP(ILG),   WTSSTP(ILG),   WTGSTP(ILG)
C
C     * CTEM-RELATED FIELDS (NOT USED IN STANDARD OFFLINE CLASS RUNS).
C
      REAL AILCG(ILG,ICTEM),   AILCGS(ILG,ICTEM),  FCANC(ILG,ICTEM),
     1     FCANCS(ILG,ICTEM),  CO2CONC(ILG),       CO2I1CG(ILG,ICTEM),
     2     CO2I1CS(ILG,ICTEM), CO2I2CG(ILG,ICTEM), CO2I2CS(ILG,ICTEM),
     3     COSZS(ILG),         XDIFFUSC(ILG),       SLAI(ILG,ICTEM),
     4     RMATCTEM(ILG,ICTEM,IGND),               FCANCMX(ILG,ICTEM),
     5     ANCSVEG(ILG,ICTEM), ANCGVEG(ILG,ICTEM), RMLCSVEG(ILG,ICTEM),
     6     RMLCGVEG(ILG,ICTEM),  CFLUXCG(ILG),     CFLUXCS(ILG),
     7     RMATC(ILG,ICAN,IGND), AILC  (ILG,ICAN), PAIC (ILG,ICAN),
     8     FIELDSM(ILG,IGND),  WILTSM(ILG,IGND)
C
      INTEGER ICTEMMOD, L2MAX, NOL2PFTS(ICAN)
C
C     * CONSTANTS AND TEMPORARY VARIABLES.
C
      REAL DEGLAT,DEGLON,FSDOWN,DAY,DECL,HOUR,COSZ,CUMSNO,EVAPSUM,
     1     QSUMV,QSUMS,QSUM1,QSUM2,QSUM3,WSUMV,WSUMS,WSUMG,ALTOT,
     2     FSSTAR,FLSTAR,QH,QE,BEG,SNOMLT,ZSN,TCN,TSN,TPN,GTOUT
C
C     * COMMON BLOCK PARAMETERS.
C
      REAL X1,X2,X3,X4,G,GAS,X5,X6,CPRES,GASV,X7,CPI,X8,CELZRO,X9,
     1     X10,X11,X12,X13,X14,X15,SIGMA,X16,DELTIM,DELT,TFREZ,
     2     RGAS,RGASV,GRAV,SBC,VKC,CT,VMIN,TCW,TCICE,TCSAND,TCCLAY,
     3     TCOM,TCDRYS,RHOSOL,RHOOM,HCPW,HCPICE,HCPSOL,HCPOM,HCPSND,
     4     HCPCLY,SPHW,SPHICE,SPHVEG,SPHAIR,RHOW,RHOICE,TCGLAC,CLHMLT,
     5     CLHVAP,PI,ZOLNG,ZOLNS,ZOLNI,ZORATG,ALVSI,ALIRI,ALVSO,ALIRO,
     6     ALBRCK,DELTA,CGRAV,CKARM,CPD,AS,ASX,CI,BS,BETA,FACTN,HMIN,
     7     ANGMAX
C
C=======================================================================
C     * PHYSICAL CONSTANTS.
C     * PARAMETERS IN THE FOLLOWING COMMON BLOCKS ARE NORMALLY DEFINED
C     * WITHIN THE GCM.

      COMMON /PARAMS/ X1,    X2,    X3,    X4,   G,GAS,   X5,
     1                X6,    CPRES, GASV,  X7
      COMMON /PARAM1/ CPI,   X8,    CELZRO,X9,    X10,    X11
      COMMON /PARAM3/ X12,   X13,   X14,   X15,   SIGMA,  X16
      COMMON  /TIMES/ DELTIM,K1,    K2,    K3,    K4,     K5,
     1                K6,    K7,    K8,    K9,    K10,    K11
C
C     * THE FOLLOWING COMMON BLOCKS ARE DEFINED SPECIFICALLY FOR USE 
C     * IN CLASS, VIA BLOCK DATA AND THE SUBROUTINE "CLASSD".
C
      COMMON /CLASS1/ DELT,TFREZ
      COMMON /CLASS2/ RGAS,RGASV,GRAV,SBC,VKC,CT,VMIN
      COMMON /CLASS3/ TCW,TCICE,TCSAND,TCCLAY,TCOM,TCDRYS,
     1                RHOSOL,RHOOM
      COMMON /CLASS4/ HCPW,HCPICE,HCPSOL,HCPOM,HCPSND,HCPCLY,
     1                SPHW,SPHICE,SPHVEG,SPHAIR,RHOW,RHOICE,
     2                TCGLAC,CLHMLT,CLHVAP
      COMMON /CLASS5/ THPORG,THRORG,THMORG,BORG,PSISORG,GRKSORG
      COMMON /CLASS6/ PI,GROWYR,ZOLNG,ZOLNS,ZOLNI,ZORAT,ZORATG
      COMMON /CLASS7/ CANEXT,XLEAF
      COMMON /CLASS8/ ALVSI,ALIRI,ALVSO,ALIRO,ALBRCK
      COMMON /PHYCON/ DELTA,CGRAV,CKARM,CPD
      COMMON /CLASSD2/ AS,ASX,CI,BS,BETA,FACTN,HMIN,ANGMAX
C
      CALL CLASSD
C
      ZDMROW(1)=10.0
      ZDHROW(1)=2.0
      CUMSNO=0.0
C
C     * THE FOLLOWING SWITCHES SELECT DIFFERENT RUN OPTIONS.
C
C     * IF IDISP=0, VEGETATION DISPLACEMENT HEIGHTS ARE IGNORED,
C     * BECAUSE THE ATMOSPHERIC MODEL CONSIDERS THESE TO BE PART
C     * OF THE "TERRAIN".
C     * IF IDISP=1, VEGETATION DISPLACEMENT HEIGHTS ARE CALCULATED.
C
C     * IF IZREF=1, THE BOTTOM OF THE ATMOSPHERIC MODEL IS TAKEN
C     * TO LIE AT THE GROUND SURFACE.
C     * IF IZREF=2, THE BOTTOM OF THE ATMOSPHERIC MODEL IS TAKEN
C     * TO LIE AT THE LOCAL ROUGHNESS HEIGHT.
C
C     * IF ISLFD=0, DRCOEF IS CALLED FOR SURFACE STABILITY CORRECTIONS
C     * AND THE ORIGINAL GCM SET OF SCREEN-LEVEL DIAGNOSTIC CALCULATIONS 
C     * IS DONE.
C     * IF ISLFD=1, DRCOEF IS CALLED FOR SURFACE STABILITY CORRECTIONS
C     * AND SLDIAG IS CALLED FOR SCREEN-LEVEL DIAGNOSTIC CALCULATIONS. 
C     * IF ISLFD=2, FLXSURFZ IS CALLED FOR SURFACE STABILITY CORRECTIONS
C     * AND DIASURF IS CALLED FOR SCREEN-LEVEL DIAGNOSTIC CALCULATIONS. 
C
C     * IF IPCP=1, THE RAINFALL-SNOWFALL CUTOFF IS TAKEN TO LIE AT 0 C.
C     * IF IPCP=2, A LINEAR PARTITIONING OF PRECIPITATION BETWEEEN 
C     * RAINFALL AND SNOWFALL IS DONE BETWEEN 0 C AND 2 C.
C     * IF IPCP=3, RAINFALL AND SNOWFALL ARE PARTITIONED ACCORDING TO
C     * A POLYNOMIAL CURVE BETWEEN 0 C AND 6 C.
C     * IF IPCP=4, THE RAINFALL, SNOWFALL AND TOTAL PRECIPITATION RATES
C     * ARE READ IN DIRECTLY.
C
C     * ITC, ITCG AND ITG ARE SWITCHES TO CHOOSE THE ITERATION SCHEME TO
C     * BE USED IN CALCULATING THE CANOPY OR GROUND SURFACE TEMPERATURE
C     * RESPECTIVELY.  IF THE SWITCH IS SET TO 1, A BISECTION METHOD IS
C     * USED; IF TO 2, THE NEWTON-RAPHSON METHOD IS USED.
C     
C     * IF IWF=0, ONLY OVERLAND FLOW AND BASEFLOW ARE MODELLED, AND
C     * THE GROUND SURFACE SLOPE IS NOT MODELLED.
C     * IF IWF=n (0<n<4), THE WATFLOOD CALCULATIONS OF OVERLAND FLOW 
C     * AND INTERFLOW ARE PERFORMED; INTERFLOW IS DRAWN FROM THE TOP 
C     * n SOIL LAYERS.
C
C     * IF IPAI, IHGT, IALC, IALS AND IALG ARE ZERO, THE VALUES OF 
C     * PLANT AREA INDEX, VEGETATION HEIGHT, CANOPY ALBEDO, SNOW ALBEDO
C     * AND SOIL ALBEDO RESPECTIVELY CALCULATED BY CLASS ARE USED.
C     * IF ANY OF THESE SWITCHES IS SET TO 1, THE VALUE OF THE
C     * CORRESPONDING PARAMETER CALCULATED BY CLASS IS OVERRIDDEN BY
C     * A USER-SUPPLIED INPUT VALUE.
C
C     * ICTEMMOD IS SET TO 1 IF CLASS IS BEING RUN IN CONJUNCTION WITH
C     * THE CANADIAN TERRESTRIAL ECOSYSTEM MODEL "CTEM"; OTHERWISE
C     * ICTEMMOD IS SET TO 0.
C      
      IDISP=1
      IZREF=1
      ISLFD=2
      IPCP=1
      ITC=2
      ITCG=2
      ITG=2
      IWF=0
      IPAI=0
      IHGT=0
      IALC=0
      IALS=0
      IALG=0
      ICTEMMOD=0

C=======================================================================
C     * OPEN FILES FOR READING AND WRITING.

      OPEN(UNIT=50,FILE='CLASS_benchmark.ini',
     1             STATUS='OLD')
      OPEN(UNIT=51,FILE='CLASS_benchmark.met',STATUS='OLD')
      OPEN(UNIT=52,FILE='Soil_3lev',STATUS='OLD')
      OPEN(UNIT=61,FILE='CLASS_benchmark.of1')
      OPEN(UNIT=62,FILE='CLASS_benchmark.of2')
      OPEN(UNIT=63,FILE='CLASS_benchmark.of3')
      OPEN(UNIT=64,FILE='CLASS_benchmark.of4')
      OPEN(UNIT=65,FILE='CLASS_benchmark.of5')
      OPEN(UNIT=66,FILE='CLASS_benchmark.of6')
      OPEN(UNIT=67,FILE='CLASS_benchmark.of7')
      OPEN(UNIT=68,FILE='CLASS_benchmark.of8')
      OPEN(UNIT=69,FILE='CLASS_benchmark.of9')

C     * READ AND PROCESS INITIALIZATION AND BACKGROUND INFORMATION.
C     * FIRST, MODEL RUN SPECIFICATIONS.

      READ (50,5010) TITLE1,TITLE2,TITLE3,TITLE4,TITLE5,TITLE6
      READ (50,5010) NAME1,NAME2,NAME3,NAME4,NAME5,NAME6
      READ (50,5010) PLACE1,PLACE2,PLACE3,PLACE4,PLACE5,PLACE6
      WRITE(61,6001) TITLE1,TITLE2,TITLE3,TITLE4,TITLE5,TITLE6
      WRITE(61,6002) NAME1,NAME2,NAME3,NAME4,NAME5,NAME6
      WRITE(61,6011) 
6011  FORMAT(2X,'DAY  YEAR  K*  L*  QH  QE  SM  QG  ',
     1          'TR  SWE  DS  WS  AL  ROF  CUMS')
      WRITE(62,6001) TITLE1,TITLE2,TITLE3,TITLE4,TITLE5,TITLE6
      WRITE(62,6002) NAME1,NAME2,NAME3,NAME4,NAME5,NAME6
      IF(IGND.GT.3) THEN
          WRITE(62,6012)
6012      FORMAT(2X,'DAY  YEAR  TG1  THL1  THI1  TG2  THL2  THI2  ',
     1              'TG3  THL3  THI3  TG4  THL4  THI4  TG5  THL5  ',
     2              'THI5')
      ELSE
          WRITE(62,6212)
6212      FORMAT(2X,'DAY  YEAR  TG1  THL1  THI1  TG2  THL2  THI2  ',
     1              'TG3  THL3  THI3  TCN  RCAN  SCAN  TSN  ZSN')
      ENDIF
      WRITE(63,6001) TITLE1,TITLE2,TITLE3,TITLE4,TITLE5,TITLE6
      WRITE(63,6002) NAME1,NAME2,NAME3,NAME4,NAME5,NAME6
      IF(IGND.GT.3) THEN
          WRITE(63,6013)
6013      FORMAT(2X,'DAY  YEAR  TG6  THL6  THI6  TG7  THL7  THI7  ',
     1              'TG8  THL8  THI8  TG9  THL9  THI9  TG10'  ,
     2              'THL10  THI10')
      ELSE
          WRITE(63,6313)
6313      FORMAT(2X,'DAY YEAR KIN LIN TA UV PRES QA PCP EVAP')
      ENDIF
C
      WRITE(64,6001) TITLE1,TITLE2,TITLE3,TITLE4,TITLE5,TITLE6
      WRITE(64,6002) NAME1,NAME2,NAME3,NAME4,NAME5,NAME6
      WRITE(64,6014) 
6014  FORMAT(2X,'HOUR  MIN  DAY  YEAR  K*  L*  QH  QE  SM  QG  ',
     1          'TR  SWE  DS  WS  AL  ROF  TPN  ZPN')
      WRITE(65,6001) TITLE1,TITLE2,TITLE3,TITLE4,TITLE5,TITLE6
      WRITE(65,6002) NAME1,NAME2,NAME3,NAME4,NAME5,NAME6
      IF(IGND.GT.3) THEN
          WRITE(65,6015) 
6015      FORMAT(2X,'HOUR  MIN  DAY  YEAR  TG1  THL1  THI1  TG2  ',
     1          'THL2  THI2  TG3  THL3  THI3  TG4  THL4  THI4  ',
     2          'TG5  THL5  THI5')
      ELSE
          WRITE(65,6515)
6515      FORMAT(2X,'HOUR  MIN  DAY  YEAR  TG1  THL1  THI1  TG2  ',
     1           'THL2  THI2  TG3  THL3  THI3  TCN  RCAN  SCAN  ',
     2           'TSN  ZSN  TSF')
      ENDIF
      WRITE(66,6001) TITLE1,TITLE2,TITLE3,TITLE4,TITLE5,TITLE6
      WRITE(66,6002) NAME1,NAME2,NAME3,NAME4,NAME5,NAME6
      IF(IGND.GT.3) THEN
          WRITE(66,6016) 
6016      FORMAT(2X,'HOUR  MIN  DAY  YEAR  TG6  THL6  THI6  TG7  ',
     1          'THL7  THI7  TG8  THL8  THI8  TG9  THL9  THI9  ',
     2          'TG10  THL10  THI10  G0  G1  G2  G3  G4  G5  G6  ',
     3          'G7  G8  G9')
      ELSE
          WRITE(66,6616)
6616      FORMAT(2X,'HOUR  MIN  DAY  SWIN  LWIN  PCP  TA  VA  PA  QA')
      ENDIF
      WRITE(67,6001) TITLE1,TITLE2,TITLE3,TITLE4,TITLE5,TITLE6
      WRITE(67,6002) NAME1,NAME2,NAME3,NAME4,NAME5,NAME6
      WRITE(67,6017)
6017  FORMAT(2X,'WCAN SCAN CWLCAP CWFCAP FC FG FCS FGS CDH ',
     1          'TCANO TCANS ALBS')
      WRITE(68,6001) TITLE1,TITLE2,TITLE3,TITLE4,TITLE5,TITLE6
      WRITE(68,6002) NAME1,NAME2,NAME3,NAME4,NAME5,NAME6
      WRITE(68,6018) 
6018  FORMAT(2X,'FSGV FSGS FSGG FLGV FLGS FLGG HFSC HFSS HFSG ',
     1          'HEVC HEVS HEVG HMFC HMFS HMFG1 HMFG2 HMFG3 ',
     2          'HTCC HTCS HTC1 HTC2 HTC3')
      WRITE(69,6001) TITLE1,TITLE2,TITLE3,TITLE4,TITLE5,TITLE6
      WRITE(69,6002) NAME1,NAME2,NAME3,NAME4,NAME5,NAME6
      WRITE(69,6019) 
6019  FORMAT(2X,'PCFC PCLC PCPN PCPG QFCF QFCL QFN QFG QFC1 ',
     1          'QFC2 QFC3 ROFC ROFN ROFO ROF WTRC WTRS WTRG EVDF ',
     2          'CTV CTS CT1 CT2 CT3')
C
      DO 25 J=1,IGND
          READ(52,5002) DELZ(J),ZBOT(J)
 25   CONTINUE
5002  FORMAT(2X,2F8.2)
      
      READ(50,5020) DEGLAT,DEGLON,ZRFMROW(1),ZRFHROW(1),ZBLDROW(1),
     1              GCROW(1),NLTEST,NMTEST
      JLAT=NINT(DEGLAT)
      RADJROW(1)=DEGLAT*PI/180.
      DLONROW(1)=DEGLON
      Z0ORROW(1)=0.0
      GGEOROW(1)=0.0
C      GGEOROW(1)=-0.035

      DO 50 I=1,NLTEST
      DO 50 M=1,NMTEST
          READ(50,5040) (FCANROT(I,M,J),J=1,ICAN+1),(PAMXROT(I,M,J),
     1                  J=1,ICAN)
          READ(50,5040) (LNZ0ROT(I,M,J),J=1,ICAN+1),(PAMNROT(I,M,J),
     1                  J=1,ICAN)
          READ(50,5040) (ALVCROT(I,M,J),J=1,ICAN+1),(CMASROT(I,M,J),
     1                  J=1,ICAN)
          READ(50,5040) (ALICROT(I,M,J),J=1,ICAN+1),(ROOTROT(I,M,J),
     1                  J=1,ICAN)
          READ(50,5030) (RSMNROT(I,M,J),J=1,ICAN),
     1                  (QA50ROT(I,M,J),J=1,ICAN)
          READ(50,5030) (VPDAROT(I,M,J),J=1,ICAN),
     1                  (VPDBROT(I,M,J),J=1,ICAN)
          READ(50,5030) (PSGAROT(I,M,J),J=1,ICAN),
     1                  (PSGBROT(I,M,J),J=1,ICAN)
          READ(50,5040) DRNROT(I,M),SDEPROT(I,M),FAREROT(I,M)
          READ(50,5090) XSLPROT(I,M),GRKFROT(I,M),WFSFROT(I,M),
     1                  WFCIROT(I,M),MIDROT(I,M)
          READ(50,5080) (SANDROT(I,M,J),J=1,3)
          READ(50,5080) (CLAYROT(I,M,J),J=1,3)
          READ(50,5080) (ORGMROT(I,M,J),J=1,3)
          READ(50,5050) (TBARROT(I,M,J),J=1,3),TCANROT(I,M),
     1                  TSNOROT(I,M),TPNDROT(I,M)
          READ(50,5060) (THLQROT(I,M,J),J=1,3),(THICROT(I,M,J),
     1                  J=1,3),ZPNDROT(I,M)
          READ(50,5070) RCANROT(I,M),SCANROT(I,M),SNOROT(I,M),
     1                  ALBSROT(I,M),RHOSROT(I,M),GROROT(I,M)
50    CONTINUE

      DO 100 I=1,NLTEST
      DO 100 M=1,NMTEST
          TBARROT(I,M,1)=TBARROT(I,M,1)+TFREZ
          TBARROT(I,M,2)=TBARROT(I,M,2)+TFREZ
          TBARROT(I,M,3)=TBARROT(I,M,3)+TFREZ
          TSNOROT(I,M)=TSNOROT(I,M)+TFREZ
          TCANROT(I,M)=TCANROT(I,M)+TFREZ
          TPNDROT(I,M)=TPNDROT(I,M)+TFREZ
          TBASROT(I,M)=TBARROT(I,M,3)
          CMAIROT(I,M)=0.
          WSNOROT(I,M)=0.
          ZSNLROT(I,M)=0.10
          TSFSROT(I,M,1)=TFREZ
          TSFSROT(I,M,2)=TFREZ
          TSFSROT(I,M,3)=TBARROT(I,M,1)
          TSFSROT(I,M,4)=TBARROT(I,M,1)
          TACROT (I,M)=TCANROT(I,M)
          QACROT (I,M)=0.5E-2
          IF(IGND.GT.3)                                 THEN
              DO 65 J=4,IGND
                  TBARROT(I,M,J)=TBARROT(I,M,3)
                  IF(SDEPROT(I,M).LT.(ZBOT(J-1)+0.001) .AND.
     1                  SANDROT(I,M,3).GT.-2.5)     THEN
                      SANDROT(I,M,J)=-3.0
                      CLAYROT(I,M,J)=-3.0
                      ORGMROT(I,M,J)=-3.0
                      THLQROT(I,M,J)=0.0
                      THICROT(I,M,J)=0.0
                  ELSE
                      SANDROT(I,M,J)=SANDROT(I,M,3)
                      CLAYROT(I,M,J)=CLAYROT(I,M,3)
                      ORGMROT(I,M,J)=ORGMROT(I,M,3)
                      THLQROT(I,M,J)=THLQROT(I,M,3)
                      THICROT(I,M,J)=THICROT(I,M,3)
                  ENDIF
65            CONTINUE
          ENDIF
          DO 75 K=1,6
          DO 75 L=1,50
              ITCTROT(I,M,K,L)=0
75        CONTINUE
100   CONTINUE
      
      DO 150 I=1,NLTEST
          PREACC(I)=0.
          GTACC(I)=0.
          QEVPACC(I)=0.
          EVAPACC(I)=0.
          HFSACC(I)=0.
          HMFNACC(I)=0.
          ROFACC(I)=0.
          OVRACC(I)=0.
          WTBLACC(I)=0.
          ALVSACC(I)=0.
          ALIRACC(I)=0.
          RHOSACC(I)=0.
          SNOACC(I)=0.
          WSNOACC(I)=0.
          CANARE(I)=0.
          SNOARE(I)=0.
          TSNOACC(I)=0.
          TCANACC(I)=0.
          RCANACC(I)=0.
          SCANACC(I)=0.
          GROACC(I)=0.
          FSINACC(I)=0.
          FLINACC(I)=0.
          FLUTACC(I)=0.
          TAACC(I)=0.
          UVACC(I)=0.
          PRESACC(I)=0.
          QAACC(I)=0.
          DO 125 J=1,IGND
              TBARACC(I,J)=0.
              THLQACC(I,J)=0.
              THICACC(I,J)=0.
              THALACC(I,J)=0.
125       CONTINUE
150   CONTINUE

      CALL CLASSB(THPROT,THRROT,THMROT,BIROT,PSISROT,GRKSROT,
     1            THRAROT,HCPSROT,TCSROT,THFCROT,PSIWROT,
     2            DLZWROT,ZBTWROT,ALGWROT,ALGDROT,
     3            SANDROT,CLAYROT,ORGMROT,DELZ,ZBOT,
     4            SDEPROT,ISNDROT,IGDRROT,
     5            NLAT,NMOS,1,NLTEST,NMTEST,IGND,ICTEMMOD)

5010  FORMAT(2X,6A4)
5020  FORMAT(5F10.2,F7.1,3I5)
5030  FORMAT(4F8.3,8X,4F8.3)
5040  FORMAT(9F8.3)
5050  FORMAT(6F10.2)
5060  FORMAT(7F10.3)
5070  FORMAT(2F10.4,F10.2,F10.3,F10.4,F10.3)
5080  FORMAT(3F10.1)
5090  FORMAT(4E8.1,I8)
5200  FORMAT(4I10)
C5300  FORMAT(1X,2I2,I5,I6,2F9.2,E14.4,F9.2,E12.3,F8.2,F12.2,3F9.2,
5300  FORMAT(1X,I2,I3,I5,I6,2F9.2,E14.4,F9.2,E12.3,F8.2,F12.2,3F9.2,
     1       F9.4)
6001  FORMAT('CLASS TEST RUN:     ',6A4)
6002  FORMAT('RESEARCHER:         ',6A4)
6003  FORMAT('INSTITUTION:        ',6A4)

C=======================================================================
C     * LAUNCH RUN.

      N=0
      NCOUNT=1
      NDAY=86400/NINT(DELT)

200   CONTINUE
C
C========================================================================
C     * READ IN METEOROLOGICAL FORCING DATA FOR CURRENT TIME STEP;
C     * CALCULATE SOLAR ZENITH ANGLE AND COMPONENTS OF INCOMING SHORT-
C     * WAVE RADIATION FLUX; ESTIMATE FLUX PARTITIONS IF NECESSARY.
C
      N=N+1
      DO 250 I=1,NLTEST
          READ(51,5300,END=999) IHOUR,IMIN,IDAY,IYEAR,FSDOWN,FDLROW(I),
     1         PREROW(I),TAROW(I),QAROW(I),UVROW(I),PRESROW(I)
          FSVHROW(I)=0.5*FSDOWN
          FSIHROW(I)=0.5*FSDOWN
          TAROW(I)=TAROW(I)+TFREZ
          ULROW(I)=UVROW(I)
          VLROW(I)=0.0
          UVROW(I)=MAX(VMIN,UVROW(I))
          VMODROW(I)=UVROW(I)
250   CONTINUE
C
      DAY=REAL(IDAY)+(REAL(IHOUR)+REAL(IMIN)/60.)/24.
      DECL=SIN(2.*PI*(284.+DAY)/365.)*23.45*PI/180.
      HOUR=(REAL(IHOUR)+REAL(IMIN)/60.)*PI/12.-PI
      COSZ=SIN(RADJROW(1))*SIN(DECL)+COS(RADJROW(1))*COS(DECL)*COS(HOUR)

      DO 300 I=1,NLTEST
          CSZROW(I)=SIGN(MAX(ABS(COSZ),1.0E-3),COSZ)
          IF(PREROW(I).GT.0.) THEN
              XDIFFUS(I)=1.0
          ELSE
              XDIFFUS(I)=MAX(0.0,MIN(1.0-0.9*COSZ,1.0))
          ENDIF
          FCLOROW(I)=XDIFFUS(I)
300   CONTINUE
C
      CALL CLASSI(VPDROW,TADPROW,PADRROW,RHOAROW,RHSIROW,
     1            RPCPROW,TRPCROW,SPCPROW,TSPCROW,TAROW,QAROW,
     2            PREROW,RPREROW,SPREROW,PRESROW,
     3            IPCP,NLAT,1,NLTEST)
C
      CUMSNO=CUMSNO+SPCPROW(1)*RHSIROW(1)*DELT
C
      CALL GATPREP(ILMOS,JLMOS,IWMOS,JWMOS,
     1             NML,NMW,GCROW,FAREROT,MIDROT,
     2             NLAT,NMOS,ILG,1,NLTEST,NMTEST)
C
      CALL CLASSG (TBARGAT,THLQGAT,THICGAT,TPNDGAT,ZPNDGAT,
     1             TBASGAT,ALBSGAT,TSNOGAT,RHOSGAT,SNOGAT, 
     2             TCANGAT,RCANGAT,SCANGAT,GROGAT, CMAIGAT, 
     3             FCANGAT,LNZ0GAT,ALVCGAT,ALICGAT,PAMXGAT,
     4             PAMNGAT,CMASGAT,ROOTGAT,RSMNGAT,QA50GAT,
     5             VPDAGAT,VPDBGAT,PSGAGAT,PSGBGAT,PAIDGAT,
     6             HGTDGAT,ACVDGAT,ACIDGAT,TSFSGAT,WSNOGAT,
     7             THPGAT, THRGAT, THMGAT, BIGAT,  PSISGAT,
     8             GRKSGAT,THRAGAT,HCPSGAT,TCSGAT, IGDRGAT,
     9             THFCGAT,PSIWGAT,DLZWGAT,ZBTWGAT,VMODGAT,
     A             ZSNLGAT,ZPLGGAT,ZPLSGAT,TACGAT, QACGAT,
     B             DRNGAT, XSLPGAT,GRKFGAT,WFSFGAT,WFCIGAT,
     C             ALGWGAT,ALGDGAT,ASVDGAT,ASIDGAT,AGVDGAT,
     D             AGIDGAT,ISNDGAT,RADJGAT,ZBLDGAT,Z0ORGAT,
     E             ZRFMGAT,ZRFHGAT,ZDMGAT, ZDHGAT, FSVHGAT,
     F             FSIHGAT,CSZGAT, FDLGAT, ULGAT,  VLGAT,  
     G             TAGAT,  QAGAT,  PRESGAT,PREGAT, PADRGAT,
     H             VPDGAT, TADPGAT,RHOAGAT,RPCPGAT,TRPCGAT,
     I             SPCPGAT,TSPCGAT,RHSIGAT,FCLOGAT,DLONGAT,
     J             GGEOGAT,
     K             ILMOS,JLMOS,IWMOS,JWMOS,
     L             NML,NLAT,NMOS,ILG,IGND,ICAN,ICAN+1,
     M             TBARROT,THLQROT,THICROT,TPNDROT,ZPNDROT,
     N             TBASROT,ALBSROT,TSNOROT,RHOSROT,SNOROT, 
     O             TCANROT,RCANROT,SCANROT,GROROT, CMAIROT,
     P             FCANROT,LNZ0ROT,ALVCROT,ALICROT,PAMXROT,
     Q             PAMNROT,CMASROT,ROOTROT,RSMNROT,QA50ROT,
     R             VPDAROT,VPDBROT,PSGAROT,PSGBROT,PAIDROT,
     S             HGTDROT,ACVDROT,ACIDROT,TSFSROT,WSNOROT,
     T             THPROT, THRROT, THMROT, BIROT,  PSISROT,
     U             GRKSROT,THRAROT,HCPSROT,TCSROT, IGDRROT,
     V             THFCROT,PSIWROT,DLZWROT,ZBTWROT,VMODROW,
     W             ZSNLROT,ZPLGROT,ZPLSROT,TACROT, QACROT,
     X             DRNROT, XSLPROT,GRKFROT,WFSFROT,WFCIROT,
     Y             ALGWROT,ALGDROT,ASVDROT,ASIDROT,AGVDROT,
     Z             AGIDROT,ISNDROT,RADJROW,ZBLDROW,Z0ORROW,
     +             ZRFMROW,ZRFHROW,ZDMROW, ZDHROW, FSVHROW,
     +             FSIHROW,CSZROW, FDLROW, ULROW,  VLROW,  
     +             TAROW,  QAROW,  PRESROW,PREROW, PADRROW,
     +             VPDROW, TADPROW,RHOAROW,RPCPROW,TRPCROW,
     +             SPCPROW,TSPCROW,RHSIROW,FCLOROW,DLONROW,
     +             GGEOROW  )
C
C    * INITIALIZATION OF DIAGNOSTIC VARIABLES SPLIT OUT OF CLASSG
C    * FOR CONSISTENCY WITH GCM APPLICATIONS.
C
      DO 320 K=1,ILG
          CDHGAT (K)=0.0
          CDMGAT (K)=0.0
          HFSGAT (K)=0.0
          TFXGAT (K)=0.0
          QEVPGAT(K)=0.0
          QFSGAT (K)=0.0
          QFXGAT (K)=0.0
          PETGAT (K)=0.0
          GAGAT  (K)=0.0
          EFGAT  (K)=0.0
          GTGAT  (K)=0.0
          QGGAT  (K)=0.0
          ALVSGAT(K)=0.0
          ALIRGAT(K)=0.0
          SFCTGAT(K)=0.0
          SFCUGAT(K)=0.0
          SFCVGAT(K)=0.0
          SFCQGAT(K)=0.0
          FSNOGAT(K)=0.0
          FSGVGAT(K)=0.0
          FSGSGAT(K)=0.0
          FSGGGAT(K)=0.0
          FLGVGAT(K)=0.0
          FLGSGAT(K)=0.0
          FLGGGAT(K)=0.0
          HFSCGAT(K)=0.0
          HFSSGAT(K)=0.0
          HFSGGAT(K)=0.0
          HEVCGAT(K)=0.0
          HEVSGAT(K)=0.0
          HEVGGAT(K)=0.0
          HMFCGAT(K)=0.0
          HMFNGAT(K)=0.0
          HTCCGAT(K)=0.0
          HTCSGAT(K)=0.0
          PCFCGAT(K)=0.0
          PCLCGAT(K)=0.0
          PCPNGAT(K)=0.0
          PCPGGAT(K)=0.0
          QFGGAT (K)=0.0
          QFNGAT (K)=0.0
          QFCFGAT(K)=0.0
          QFCLGAT(K)=0.0
          ROFGAT (K)=0.0
          ROFOGAT(K)=0.0
          ROFSGAT(K)=0.0
          ROFBGAT(K)=0.0
          TROFGAT (K)=0.0
          TROOGAT(K)=0.0
          TROSGAT(K)=0.0
          TROBGAT(K)=0.0
          ROFCGAT(K)=0.0
          ROFNGAT(K)=0.0
          ROVGGAT(K)=0.0
          WTRCGAT(K)=0.0
          WTRSGAT(K)=0.0
          WTRGGAT(K)=0.0
          DRGAT  (K)=0.0
320   CONTINUE
C
      DO 340 L=1,IGND
      DO 330 K=1,ILG
          HMFGGAT(K,L)=0.0
          HTCGAT (K,L)=0.0
          QFCGAT (K,L)=0.0
          GFLXGAT(K,L)=0.0
330   CONTINUE
340   CONTINUE
C
      DO 370 M=1,50
          DO 360 L=1,6
              DO 350 K=1,NML
                  ITCTGAT(K,L,M)=0
350           CONTINUE
360       CONTINUE
370   CONTINUE
C
C========================================================================
C
      CALL CLASSZ (0,      CTVSTP, CTSSTP, CT1STP, CT2STP, CT3STP, 
     1             WTVSTP, WTSSTP, WTGSTP,
     2             FSGVGAT,FLGVGAT,HFSCGAT,HEVCGAT,HMFCGAT,HTCCGAT,
     3             FSGSGAT,FLGSGAT,HFSSGAT,HEVSGAT,HMFNGAT,HTCSGAT,
     4             FSGGGAT,FLGGGAT,HFSGGAT,HEVGGAT,HMFGGAT,HTCGAT,
     5             PCFCGAT,PCLCGAT,QFCFGAT,QFCLGAT,ROFCGAT,WTRCGAT,
     6             PCPNGAT,QFNGAT, ROFNGAT,WTRSGAT,PCPGGAT,QFGGAT,
     7             QFCGAT, ROFGAT, WTRGGAT,CMAIGAT,RCANGAT,SCANGAT,   
     8             TCANGAT,SNOGAT, WSNOGAT,TSNOGAT,THLQGAT,THICGAT,  
     9             HCPSGAT,THPGAT, DLZWGAT,TBARGAT,ZPNDGAT,TPNDGAT,  
     A             DELZ,   FCS,    FGS,    FC,     FG,
     B             1,      NML,    ILG,    IGND,   N    )
C
C========================================================================
C
C     * ALBEDO AND TRANSMISSIVITY CALCULATIONS; GENERAL VEGETATION
C     * CHARACTERISTICS.
C
      CALL CLASSA    (FC,     FG,     FCS,    FGS,    ALVSCN, ALIRCN,
     1                ALVSG,  ALIRG,  ALVSCS, ALIRCS, ALVSSN, ALIRSN,           
     2                ALVSGC, ALIRGC, ALVSSC, ALIRSC, TRVSCN, TRIRCN, 
     3                TRVSCS, TRIRCS, FSVF,   FSVFS,  
     4                RAICAN, RAICNS, SNOCAN, SNOCNS, FRAINC, FSNOWC, 
     5                FRAICS, FSNOCS, DISP,   DISPS,  ZOMLNC, ZOMLCS, 
     6                ZOELNC, ZOELCS, ZOMLNG, ZOMLNS, ZOELNG, ZOELNS, 
     7                CHCAP,  CHCAPS, CMASSC, CMASCS, CWLCAP, CWFCAP,
     8                CWLCPS, CWFCPS, RC,     RCS,    RBCOEF, FROOT,  
     9                ZPLIMC, ZPLIMG, ZPLMCS, ZPLMGS, TRSNOW, ZSNOW,  
     A                WSNOGAT,ALVSGAT,ALIRGAT,HTCCGAT,HTCSGAT,HTCGAT, 
     B                WTRCGAT,WTRSGAT,WTRGGAT,CMAIGAT,FSNOGAT,
     C                FCANGAT,LNZ0GAT,ALVCGAT,ALICGAT,PAMXGAT,PAMNGAT,
     D                CMASGAT,ROOTGAT,RSMNGAT,QA50GAT,VPDAGAT,VPDBGAT,
     E                PSGAGAT,PSGBGAT,PAIDGAT,HGTDGAT,ACVDGAT,ACIDGAT, 
     F                ASVDGAT,ASIDGAT,AGVDGAT,AGIDGAT,ALGWGAT,ALGDGAT, 
     G                THLQGAT,THICGAT,TBARGAT,RCANGAT,SCANGAT,TCANGAT,   
     H                GROGAT, SNOGAT, TSNOGAT,RHOSGAT,ALBSGAT,ZBLDGAT,
     I                Z0ORGAT,ZSNLGAT,ZPLGGAT,ZPLSGAT,
     J                FCLOGAT,TAGAT,  VPDGAT, RHOAGAT,CSZGAT, 
     K                FSVHGAT,RADJGAT,DLONGAT,RHSIGAT,DELZ,   DLZWGAT,
     L                ZBTWGAT,THPGAT, THMGAT, PSISGAT,BIGAT,  PSIWGAT,
     M                HCPSGAT,ISNDGAT,
     N                FCANCMX,ICTEM,  ICTEMMOD,       RMATC,
     O                AILC,   PAIC,   L2MAX,  NOL2PFTS,
     P                AILCG,  AILCGS, FCANC,  FCANCS,
     Q                IDAY,   ILG,    1,      NML,    
     R                JLAT,N, ICAN,   ICAN+1, IGND,   IDISP,  IZREF,
     S                IWF,    IPAI,   IHGT,   IALC,   IALS,   IALG  )
C
C-----------------------------------------------------------------------
C          * SURFACE TEMPERATURE AND FLUX CALCULATIONS.
C
      CALL  CLASST     (TBARC,  TBARG,  TBARCS, TBARGS, THLIQC, THLIQG,
     1  THICEC, THICEG, HCPC,   HCPG,   TCTOPC, TCBOTC, TCTOPG, TCBOTG, 
     2  GZEROC, GZEROG, GZROCS, GZROGS, G12C,   G12G,   G12CS,  G12GS,  
     3  G23C,   G23G,   G23CS,  G23GS,  QFREZC, QFREZG, QMELTC, QMELTG, 
     4  EVAPC,  EVAPCG, EVAPG,  EVAPCS, EVPCSG, EVAPGS, TCANO,  TCANS,  
     5  RAICAN, SNOCAN, RAICNS, SNOCNS, CHCAP,  CHCAPS, TPONDC, TPONDG, 
     6  TPNDCS, TPNDGS, TSNOCS, TSNOGS, WSNOCS, WSNOGS, RHOSCS, RHOSGS,
     7  ITCTGAT,CDHGAT, CDMGAT, HFSGAT, TFXGAT, QEVPGAT,QFSGAT, QFXGAT,  
     8  PETGAT, GAGAT,  EFGAT,  GTGAT,  QGGAT,  SFCTGAT,SFCUGAT,SFCVGAT,
     9  SFCQGAT,SFRHGAT,FSGVGAT,FSGSGAT,FSGGGAT,FLGVGAT,FLGSGAT,FLGGGAT,
     A  HFSCGAT,HFSSGAT,HFSGGAT,HEVCGAT,HEVSGAT,HEVGGAT,HMFCGAT,HMFNGAT,
     B  HTCCGAT,HTCSGAT,HTCGAT, QFCFGAT,QFCLGAT,DRGAT,  WTABGAT,ILMOGAT,
     C  UEGAT,  HBLGAT, TACGAT, QACGAT, ZRFMGAT,ZRFHGAT,ZDMGAT, ZDHGAT, 
     D  VPDGAT, TADPGAT,RHOAGAT,FSVHGAT,FSIHGAT,FDLGAT, ULGAT,  VLGAT,  
     E  TAGAT,  QAGAT,  PADRGAT,FC,     FG,     FCS,    FGS,    RBCOEF,
     F  FSVF,   FSVFS,  PRESGAT,VMODGAT,ALVSCN, ALIRCN, ALVSG,  ALIRG,  
     G  ALVSCS, ALIRCS, ALVSSN, ALIRSN, ALVSGC, ALIRGC, ALVSSC, ALIRSC,
     H  TRVSCN, TRIRCN, TRVSCS, TRIRCS, RC,     RCS,    WTRGGAT,QLWOGAT,
     I  FRAINC, FSNOWC, FRAICS, FSNOCS, CMASSC, CMASCS, DISP,   DISPS,  
     J  ZOMLNC, ZOELNC, ZOMLNG, ZOELNG, ZOMLCS, ZOELCS, ZOMLNS, ZOELNS, 
     K  TBARGAT,THLQGAT,THICGAT,TPNDGAT,ZPNDGAT,TBASGAT,TCANGAT,TSNOGAT,
     L  ZSNOW,  TRSNOW, RHOSGAT,WSNOGAT,THPGAT, THRGAT, THMGAT, THFCGAT,
     M  RADJGAT,PREGAT, HCPSGAT,TCSGAT, TSFSGAT,DELZ,   DLZWGAT,ZBTWGAT,
     N  FTEMP,  FVAP,   RIB,    ISNDGAT,
     O  AILCG,  AILCGS, FCANC,  FCANCS, CO2CONC,CO2I1CG,CO2I1CS,CO2I2CG,
     P  CO2I2CS,COSZS,  XDIFFUSC,SLAI,  ICTEM,  ICTEMMOD,RMATCTEM,
     Q  FCANCMX,L2MAX,  NOL2PFTS,       CFLUXCG,CFLUXCS,ANCSVEG,ANCGVEG,
     R  RMLCSVEG,   RMLCGVEG,   FIELDSM,WILTSM,
     S  ITC,    ITCG,   ITG,    ILG,    1,NML,  JLAT,N, ICAN,   
     T  IGND,   IZREF,  ISLFD,  NLANDCS,NLANDGS,NLANDC, NLANDG, NLANDI) 
C
C-----------------------------------------------------------------------
C          * WATER BUDGET CALCULATIONS.
C
          CALL CLASSW  (THLQGAT,THICGAT,TBARGAT,TCANGAT,RCANGAT,SCANGAT,
     1                  ROFGAT, TROFGAT,SNOGAT, TSNOGAT,RHOSGAT,ALBSGAT,
     2                  WSNOGAT,ZPNDGAT,TPNDGAT,GROGAT, TBASGAT,GFLXGAT,
     3                  PCFCGAT,PCLCGAT,PCPNGAT,PCPGGAT,QFCFGAT,QFCLGAT,
     4                  QFNGAT, QFGGAT, QFCGAT, HMFCGAT,HMFGGAT,HMFNGAT,
     5                  HTCCGAT,HTCSGAT,HTCGAT, ROFCGAT,ROFNGAT,ROVGGAT,
     6                  WTRSGAT,WTRGGAT,ROFOGAT,ROFSGAT,ROFBGAT,
     7                  TROOGAT,TROSGAT,TROBGAT,QFSGAT, 
     8                  TBARC,  TBARG,  TBARCS, TBARGS, THLIQC, THLIQG, 
     9                  THICEC, THICEG, HCPC,   HCPG,   RPCPGAT,TRPCGAT,  
     A                  SPCPGAT,TSPCGAT,PREGAT, TAGAT,  RHSIGAT,GGEOGAT,
     B                  FC,     FG,     FCS,    FGS,    TPONDC, TPONDG,
     C                  TPNDCS, TPNDGS, EVAPC,  EVAPCG, EVAPG,  EVAPCS,
     D                  EVPCSG, EVAPGS, QFREZC, QFREZG, QMELTC, QMELTG,
     E                  RAICAN, SNOCAN, RAICNS, SNOCNS, FROOT,  FSVF,   
     F                  FSVFS,  CWLCAP, CWFCAP, CWLCPS, CWFCPS, TCANO,  
     G                  TCANS,  CHCAP,  CHCAPS, CMASSC, CMASCS, ZSNOW,  
     H                  GZEROC, GZEROG, GZROCS, GZROGS, G12C,   G12G,
     I                  G12CS,  G12GS,  G23C,   G23G,   G23CS,  G23GS,
     J                  TSNOCS, TSNOGS, WSNOCS, WSNOGS, RHOSCS, RHOSGS,
     K                  ZPLIMC, ZPLIMG, ZPLMCS, ZPLMGS, TSFSGAT,
     L                  TCTOPC, TCBOTC, TCTOPG, TCBOTG, 
     M                  THPGAT, THRGAT, THMGAT, BIGAT,  PSISGAT,GRKSGAT,
     N                  THRAGAT,THFCGAT,DRNGAT, HCPSGAT,DELZ,   
     O                  DLZWGAT,ZBTWGAT,XSLPGAT,GRKFGAT,WFSFGAT,WFCIGAT,
     P                  ISNDGAT,IGDRGAT,
     Q                  IWF,    ILG,    1,      NML,    N,
     R                  JLAT,   ICAN,   IGND,   IGND+1, IGND+2,
     S                  NLANDCS,NLANDGS,NLANDC, NLANDG, NLANDI )
C

C========================================================================
C
      CALL CLASSZ (1,      CTVSTP, CTSSTP, CT1STP, CT2STP, CT3STP, 
     1             WTVSTP, WTSSTP, WTGSTP,
     2             FSGVGAT,FLGVGAT,HFSCGAT,HEVCGAT,HMFCGAT,HTCCGAT,
     3             FSGSGAT,FLGSGAT,HFSSGAT,HEVSGAT,HMFNGAT,HTCSGAT,
     4             FSGGGAT,FLGGGAT,HFSGGAT,HEVGGAT,HMFGGAT,HTCGAT,
     5             PCFCGAT,PCLCGAT,QFCFGAT,QFCLGAT,ROFCGAT,WTRCGAT,
     6             PCPNGAT,QFNGAT, ROFNGAT,WTRSGAT,PCPGGAT,QFGGAT,
     7             QFCGAT, ROFGAT, WTRGGAT,CMAIGAT,RCANGAT,SCANGAT,   
     8             TCANGAT,SNOGAT, WSNOGAT,TSNOGAT,THLQGAT,THICGAT,  
     9             HCPSGAT,THPGAT, DLZWGAT,TBARGAT,ZPNDGAT,TPNDGAT,  
     A             DELZ,   FCS,    FGS,    FC,     FG,
     B             1,      NML,    ILG,    IGND,   N    )
C
C=======================================================================

      CALL CLASSS (TBARROT,THLQROT,THICROT,GFLXROT,TSFSROT,
     1             TPNDROT,ZPNDROT,TBASROT,ALBSROT,TSNOROT,
     2             RHOSROT,SNOROT, TCANROT,RCANROT,SCANROT,
     3             GROROT, CMAIROT,TACROT, QACROT, WSNOROT,
     4             ILMOS,JLMOS,IWMOS,JWMOS,
     5             NML,NLAT,NMOS,ILG,IGND,ICAN,ICAN+1,
     6             TBARGAT,THLQGAT,THICGAT,GFLXGAT,TSFSGAT,
     7             TPNDGAT,ZPNDGAT,TBASGAT,ALBSGAT,TSNOGAT,
     8             RHOSGAT,SNOGAT, TCANGAT,RCANGAT,SCANGAT,
     9             GROGAT, CMAIGAT,TACGAT, QACGAT, WSNOGAT)
C
C    * SCATTER OPERATION ON DIAGNOSTIC VARIABLES SPLIT OUT OF 
C    * CLASSS FOR CONSISTENCY WITH GCM APPLICATIONS.
C
      DO 380 K=1,NML
          CDHROT (ILMOS(K),JLMOS(K))=CDHGAT (K)  
          CDMROT (ILMOS(K),JLMOS(K))=CDMGAT (K)  
          HFSROT (ILMOS(K),JLMOS(K))=HFSGAT (K)  
          TFXROT (ILMOS(K),JLMOS(K))=TFXGAT (K)  
          QEVPROT(ILMOS(K),JLMOS(K))=QEVPGAT(K)  
          QFSROT (ILMOS(K),JLMOS(K))=QFSGAT (K)  
          QFXROT (ILMOS(K),JLMOS(K))=QFXGAT (K)  
          PETROT (ILMOS(K),JLMOS(K))=PETGAT (K)  
          GAROT  (ILMOS(K),JLMOS(K))=GAGAT  (K)  
          EFROT  (ILMOS(K),JLMOS(K))=EFGAT  (K)  
          GTROT  (ILMOS(K),JLMOS(K))=GTGAT  (K)  
          QGROT  (ILMOS(K),JLMOS(K))=QGGAT  (K)  
          ALVSROT(ILMOS(K),JLMOS(K))=ALVSGAT(K)  
          ALIRROT(ILMOS(K),JLMOS(K))=ALIRGAT(K)  
          SFCTROT(ILMOS(K),JLMOS(K))=SFCTGAT(K)  
          SFCUROT(ILMOS(K),JLMOS(K))=SFCUGAT(K)  
          SFCVROT(ILMOS(K),JLMOS(K))=SFCVGAT(K)  
          SFCQROT(ILMOS(K),JLMOS(K))=SFCQGAT(K)  
          FSNOROT(ILMOS(K),JLMOS(K))=FSNOGAT(K)  
          FSGVROT(ILMOS(K),JLMOS(K))=FSGVGAT(K)  
          FSGSROT(ILMOS(K),JLMOS(K))=FSGSGAT(K)  
          FSGGROT(ILMOS(K),JLMOS(K))=FSGGGAT(K)  
          FLGVROT(ILMOS(K),JLMOS(K))=FLGVGAT(K)  
          FLGSROT(ILMOS(K),JLMOS(K))=FLGSGAT(K)  
          FLGGROT(ILMOS(K),JLMOS(K))=FLGGGAT(K)  
          HFSCROT(ILMOS(K),JLMOS(K))=HFSCGAT(K)  
          HFSSROT(ILMOS(K),JLMOS(K))=HFSSGAT(K)  
          HFSGROT(ILMOS(K),JLMOS(K))=HFSGGAT(K)  
          HEVCROT(ILMOS(K),JLMOS(K))=HEVCGAT(K)  
          HEVSROT(ILMOS(K),JLMOS(K))=HEVSGAT(K)  
          HEVGROT(ILMOS(K),JLMOS(K))=HEVGGAT(K)  
          HMFCROT(ILMOS(K),JLMOS(K))=HMFCGAT(K)  
          HMFNROT(ILMOS(K),JLMOS(K))=HMFNGAT(K)  
          HTCCROT(ILMOS(K),JLMOS(K))=HTCCGAT(K)  
          HTCSROT(ILMOS(K),JLMOS(K))=HTCSGAT(K)  
          PCFCROT(ILMOS(K),JLMOS(K))=PCFCGAT(K)  
          PCLCROT(ILMOS(K),JLMOS(K))=PCLCGAT(K)  
          PCPNROT(ILMOS(K),JLMOS(K))=PCPNGAT(K)  
          PCPGROT(ILMOS(K),JLMOS(K))=PCPGGAT(K)  
          QFGROT (ILMOS(K),JLMOS(K))=QFGGAT (K)  
          QFNROT (ILMOS(K),JLMOS(K))=QFNGAT (K)  
          QFCLROT(ILMOS(K),JLMOS(K))=QFCLGAT(K)  
          QFCFROT(ILMOS(K),JLMOS(K))=QFCFGAT(K)  
          ROFROT (ILMOS(K),JLMOS(K))=ROFGAT (K)  
          ROFOROT(ILMOS(K),JLMOS(K))=ROFOGAT(K)  
          ROFSROT(ILMOS(K),JLMOS(K))=ROFSGAT(K)  
          ROFBROT(ILMOS(K),JLMOS(K))=ROFBGAT(K)  
          TROFROT(ILMOS(K),JLMOS(K))=TROFGAT(K)  
          TROOROT(ILMOS(K),JLMOS(K))=TROOGAT(K)  
          TROSROT(ILMOS(K),JLMOS(K))=TROSGAT(K)  
          TROBROT(ILMOS(K),JLMOS(K))=TROBGAT(K)  
          ROFCROT(ILMOS(K),JLMOS(K))=ROFCGAT(K)  
          ROFNROT(ILMOS(K),JLMOS(K))=ROFNGAT(K)  
          ROVGROT(ILMOS(K),JLMOS(K))=ROVGGAT(K)  
          WTRCROT(ILMOS(K),JLMOS(K))=WTRCGAT(K)  
          WTRSROT(ILMOS(K),JLMOS(K))=WTRSGAT(K)  
          WTRGROT(ILMOS(K),JLMOS(K))=WTRGGAT(K)  
          DRROT  (ILMOS(K),JLMOS(K))=DRGAT  (K)  
          WTABROT(ILMOS(K),JLMOS(K))=WTABGAT(K)  
          ILMOROT(ILMOS(K),JLMOS(K))=ILMOGAT(K)  
          UEROT  (ILMOS(K),JLMOS(K))=UEGAT(K)  
          HBLROT (ILMOS(K),JLMOS(K))=HBLGAT(K)  
380   CONTINUE
C
      DO 390 L=1,IGND
      DO 390 K=1,NML
          HMFGROT(ILMOS(K),JLMOS(K),L)=HMFGGAT(K,L)
          HTCROT (ILMOS(K),JLMOS(K),L)=HTCGAT (K,L)
          QFCROT (ILMOS(K),JLMOS(K),L)=QFCGAT (K,L)
390   CONTINUE
C
      DO 430 M=1,50
          DO 420 L=1,6
              DO 410 K=1,NML
                  ITCTROT(ILMOS(K),JLMOS(K),L,M)=ITCTGAT(K,L,M)
410           CONTINUE
420       CONTINUE
430   CONTINUE
C
C=======================================================================
C     * WRITE FIELDS FROM CURRENT TIME STEP TO OUTPUT FILES.

6100  FORMAT(1X,I4,I5,9F8.2,2F8.3,F12.4,F8.2)
6200  FORMAT(1X,I4,I5,3(F8.2,2F6.3),F8.2,2F8.4,F8.2,F8.3)
6201  FORMAT(1X,I4,I5,5(F7.2,2F6.3))
6300  FORMAT(1X,I4,I5,3F9.2,F8.2,F10.2,E12.3,2F12.3,F8.3)
6400  FORMAT(1X,I2,I3,I5,I6,9F8.2,2F7.3,E11.3,F8.2,F12.4)
6500  FORMAT(1X,I2,I3,I5,I6,3(F7.2,2F6.3),F8.2,2F8.4,F8.2,2F8.3)
6600  FORMAT(1X,I2,I3,I5,2F10.2,E12.3,F10.2,F8.2,F10.2,E12.3)
6501  FORMAT(1X,I2,I3,I5,I6,5(F7.2,2F6.3))
6601  FORMAT(1X,I2,I3,I5,I6,5(F7.2,2F6.3),10F9.4)
6700  FORMAT(2X,12E11.4)
6800  FORMAT(2X,22(F10.4,2X))
6900  FORMAT(2X,(25E12.4,2X))

      DO 450 I=1,NLTEST
      DO 425 M=1,NMTEST
          IF(FSDOWN.GT.0.0) THEN
              ALTOT=(ALVSROT(I,M)+ALIRROT(I,M))/2.0
          ELSE
              ALTOT=0.0
          ENDIF
          FSSTAR=FSDOWN*(1.0-ALTOT)
          FLSTAR=FDLROW(I)-SBC*GTROT(I,M)**4
          QH=HFSROT(I,M)
          QE=QEVPROT(I,M)
C          BEG=FSSTAR+FLSTAR-QH-QE
          BEG=GFLXGAT(1,1)
          SNOMLT=HMFNROT(I,M)
          IF(RHOSROT(I,M).GT.0.0) THEN
              ZSN=SNOROT(I,M)/RHOSROT(I,M)
          ELSE
              ZSN=0.0
          ENDIF
          IF(TCANROT(I,M).GT.0.01) THEN
              TCN=TCANROT(I,M)-TFREZ
          ELSE
              TCN=0.0
          ENDIF
          IF(TSNOROT(I,M).GT.0.01) THEN
              TSN=TSNOROT(I,M)-TFREZ
          ELSE
              TSN=0.0
          ENDIF
          IF(TPNDROT(I,M).GT.0.01) THEN
              TPN=TPNDROT(I,M)-TFREZ
          ELSE
              TPN=0.0
          ENDIF
          GTOUT=GTROT(I,M)-TFREZ
          EVAPSUM=QFCFROT(I,M)+QFCLROT(I,M)+QFNROT(I,M)+QFGROT(I,M)+
     1                   QFCROT(I,M,1)+QFCROT(I,M,2)+QFCROT(I,M,3)
          WRITE(64,6400) IHOUR,IMIN,IDAY,IYEAR,FSSTAR,FLSTAR,QH,QE,
     1                   SNOMLT,BEG,GTOUT,SNOROT(I,M),RHOSROT(I,M),
     2                   WSNOROT(I,M),ALTOT,ROFROT(I,M),
     3                   TPN,ZPNDROT(I,M)
          IF(IGND.GT.3) THEN
              WRITE(65,6501) IHOUR,IMIN,IDAY,IYEAR,(TBARROT(I,M,J)-
     1                   TFREZ,THLQROT(I,M,J),THICROT(I,M,J),J=1,5)
              WRITE(66,6601) IHOUR,IMIN,IDAY,IYEAR,(TBARROT(I,M,J)-
     1                   TFREZ,THLQROT(I,M,J),THICROT(I,M,J),J=6,10),
     2                   (GFLXROT(I,M,J),J=1,10)
          ELSE
              WRITE(65,6500) IHOUR,IMIN,IDAY,IYEAR,(TBARROT(I,M,J)-
     1                   TFREZ,THLQROT(I,M,J),THICROT(I,M,J),J=1,3),
     2                   TCN,RCANROT(I,M),SCANROT(I,M),TSN,ZSN
              WRITE(66,6600) IHOUR,IMIN,IDAY,FSDOWN,FDLROW(I),PREROW(I),
     1                   TAROW(I)-TFREZ,UVROW(I),PRESROW(I),QAROW(I)
          ENDIF
          WRITE(67,6700) TROFROT(I,M),TROOROT(I,M),TROSROT(I,M),
     1                   TROBROT(I,M),ROFROT(I,M),ROFOROT(I,M),
     2                   ROFSROT(I,M),ROFBROT(I,M),
     3                   FCS(I),FGS(I),FC(I),FG(I)
          WRITE(68,6800) FSGVROT(I,M),FSGSROT(I,M),FSGGROT(I,M),
     1                   FLGVROT(I,M),FLGSROT(I,M),FLGGROT(I,M),
     2                   HFSCROT(I,M),HFSSROT(I,M),HFSGROT(I,M),
     3                   HEVCROT(I,M),HEVSROT(I,M),HEVGROT(I,M),
     4                   HMFCROT(I,M),HMFNROT(I,M),
     5                   (HMFGROT(I,M,J),J=1,3),
     6                   HTCCROT(I,M),HTCSROT(I,M),
     7                   (HTCROT(I,M,J),J=1,3)
          WRITE(69,6900) PCFCROT(I,M),PCLCROT(I,M),PCPNROT(I,M),
     1                   PCPGROT(I,M),QFCFROT(I,M),QFCLROT(I,M),
     2                   QFNROT(I,M),QFGROT(I,M),(QFCROT(I,M,J),J=1,3),
     3                   ROFCROT(I,M),ROFNROT(I,M),ROFOROT(I,M),
     4                   ROFROT(I,M),WTRCROT(I,M),WTRSROT(I,M),
     5                   WTRGROT(I,M)
425   CONTINUE
450   CONTINUE
C
C=======================================================================
C     * CALCULATE GRID CELL AVERAGE DIAGNOSTIC FIELDS.
C
      DO 525 I=1,NLTEST
          CDHROW(I)=0.
          CDMROW(I)=0.
          HFSROW(I)=0.
          TFXROW(I)=0.
          QEVPROW(I)=0.
          QFSROW(I)=0.
          QFXROW(I)=0.
          PETROW(I)=0.
          GAROW(I)=0.
          EFROW(I)=0.
          GTROW(I)=0.
          QGROW(I)=0.
          ALVSROW(I)=0.
          ALIRROW(I)=0.
          SFCTROW(I)=0.
          SFCUROW(I)=0.
          SFCVROW(I)=0.
          SFCQROW(I)=0.
          SFRHROW(I)=0.
          FSNOROW(I)=0.
          FSGVROW(I)=0.
          FSGSROW(I)=0.
          FSGGROW(I)=0.
          FLGVROW(I)=0.
          FLGSROW(I)=0.
          FLGGROW(I)=0.
          HFSCROW(I)=0.
          HFSSROW(I)=0.
          HFSGROW(I)=0.
          HEVCROW(I)=0.
          HEVSROW(I)=0.
          HEVGROW(I)=0.
          HMFCROW(I)=0.
          HMFNROW(I)=0.
          HTCCROW(I)=0.
          HTCSROW(I)=0.
          PCFCROW(I)=0.
          PCLCROW(I)=0.
          PCPNROW(I)=0.
          PCPGROW(I)=0.
          QFGROW(I)=0.
          QFNROW(I)=0.
          QFCLROW(I)=0.
          QFCFROW(I)=0.
          ROFROW(I)=0.
          ROFOROW(I)=0.
          ROFSROW(I)=0.
          ROFBROW(I)=0.
          ROFCROW(I)=0.
          ROFNROW(I)=0.
          ROVGROW(I)=0.
          WTRCROW(I)=0.
          WTRSROW(I)=0.
          WTRGROW(I)=0.
          DRROW(I)=0.
          WTABROW(I)=0.
          ILMOROW(I)=0.
          UEROW(I)=0.
          HBLROW(I)=0.
          DO 500 J=1,IGND
              HMFGROW(I,J)=0.
              HTCROW(I,J)=0.
              QFCROW(I,J)=0.
              GFLXROW(I,J)=0.
500       CONTINUE
525   CONTINUE
C
      DO 600 I=1,NLTEST
      DO 575 M=1,NMTEST
          CDHROW(I)=CDHROW(I)+CDHROT(I,M)*FAREROT(I,M)
          CDMROW(I)=CDMROW(I)+CDMROT(I,M)*FAREROT(I,M)
          HFSROW(I)=HFSROW(I)+HFSROT(I,M)*FAREROT(I,M)
          TFXROW(I)=TFXROW(I)+TFXROT(I,M)*FAREROT(I,M)
          QEVPROW(I)=QEVPROW(I)+QEVPROT(I,M)*FAREROT(I,M)
          QFSROW(I)=QFSROW(I)+QFSROT(I,M)*FAREROT(I,M)
          QFXROW(I)=QFXROW(I)+QFXROT(I,M)*FAREROT(I,M)
          PETROW(I)=PETROW(I)+PETROT(I,M)*FAREROT(I,M)
          GAROW(I)=GAROW(I)+GAROT(I,M)*FAREROT(I,M)
          EFROW(I)=EFROW(I)+EFROT(I,M)*FAREROT(I,M)
          GTROW(I)=GTROW(I)+GTROT(I,M)*FAREROT(I,M)
          QGROW(I)=QGROW(I)+QGROT(I,M)*FAREROT(I,M)
          ALVSROW(I)=ALVSROW(I)+ALVSROT(I,M)*FAREROT(I,M)
          ALIRROW(I)=ALIRROW(I)+ALIRROT(I,M)*FAREROT(I,M)
          SFCTROW(I)=SFCTROW(I)+SFCTROT(I,M)*FAREROT(I,M)
          SFCUROW(I)=SFCUROW(I)+SFCUROT(I,M)*FAREROT(I,M)
          SFCVROW(I)=SFCVROW(I)+SFCVROT(I,M)*FAREROT(I,M)
          SFCQROW(I)=SFCQROW(I)+SFCQROT(I,M)*FAREROT(I,M)
          SFRHROW(I)=SFRHROW(I)+SFRHROT(I,M)*FAREROT(I,M)
          FSNOROW(I)=FSNOROW(I)+FSNOROT(I,M)*FAREROT(I,M)
          FSGVROW(I)=FSGVROW(I)+FSGVROT(I,M)*FAREROT(I,M)
          FSGSROW(I)=FSGSROW(I)+FSGSROT(I,M)*FAREROT(I,M)
          FSGGROW(I)=FSGGROW(I)+FSGGROT(I,M)*FAREROT(I,M)
          FLGVROW(I)=FLGVROW(I)+FLGVROT(I,M)*FAREROT(I,M)
          FLGSROW(I)=FLGSROW(I)+FLGSROT(I,M)*FAREROT(I,M)
          FLGGROW(I)=FLGGROW(I)+FLGGROT(I,M)*FAREROT(I,M)
          HFSCROW(I)=HFSCROW(I)+HFSCROT(I,M)*FAREROT(I,M)
          HFSSROW(I)=HFSSROW(I)+HFSSROT(I,M)*FAREROT(I,M)
          HFSGROW(I)=HFSGROW(I)+HFSGROT(I,M)*FAREROT(I,M)
          HEVCROW(I)=HEVCROW(I)+HEVCROT(I,M)*FAREROT(I,M)
          HEVSROW(I)=HEVSROW(I)+HEVSROT(I,M)*FAREROT(I,M)
          HEVGROW(I)=HEVGROW(I)+HEVGROT(I,M)*FAREROT(I,M)
          HMFCROW(I)=HMFCROW(I)+HMFCROT(I,M)*FAREROT(I,M)
          HMFNROW(I)=HMFNROW(I)+HMFNROT(I,M)*FAREROT(I,M)
          HTCCROW(I)=HTCCROW(I)+HTCCROT(I,M)*FAREROT(I,M)
          HTCSROW(I)=HTCSROW(I)+HTCSROT(I,M)*FAREROT(I,M)
          PCFCROW(I)=PCFCROW(I)+PCFCROT(I,M)*FAREROT(I,M)
          PCLCROW(I)=PCLCROW(I)+PCLCROT(I,M)*FAREROT(I,M)
          PCPNROW(I)=PCPNROW(I)+PCPNROT(I,M)*FAREROT(I,M)
          PCPGROW(I)=PCPGROW(I)+PCPGROT(I,M)*FAREROT(I,M)
          QFGROW(I)=QFGROW(I)+QFGROT(I,M)*FAREROT(I,M)
          QFNROW(I)=QFNROW(I)+QFNROT(I,M)*FAREROT(I,M)
          QFCLROW(I)=QFCLROW(I)+QFCLROT(I,M)*FAREROT(I,M)
          QFCFROW(I)=QFCFROW(I)+QFCFROT(I,M)*FAREROT(I,M)
          ROFROW(I)=ROFROW(I)+ROFROT(I,M)*FAREROT(I,M)
          ROFOROW(I)=ROFOROW(I)+ROFOROT(I,M)*FAREROT(I,M)
          ROFSROW(I)=ROFSROW(I)+ROFSROT(I,M)*FAREROT(I,M)
          ROFBROW(I)=ROFBROW(I)+ROFBROT(I,M)*FAREROT(I,M)
          ROFCROW(I)=ROFCROW(I)+ROFCROT(I,M)*FAREROT(I,M)
          ROFNROW(I)=ROFNROW(I)+ROFNROT(I,M)*FAREROT(I,M)
          ROVGROW(I)=ROVGROW(I)+ROVGROT(I,M)*FAREROT(I,M)
          WTRCROW(I)=WTRCROW(I)+WTRCROT(I,M)*FAREROT(I,M)
          WTRSROW(I)=WTRSROW(I)+WTRSROT(I,M)*FAREROT(I,M)
          WTRGROW(I)=WTRGROW(I)+WTRGROT(I,M)*FAREROT(I,M)
          DRROW(I)=DRROW(I)+DRROT(I,M)*FAREROT(I,M)
          WTABROW(I)=WTABROW(I)+WTABROT(I,M)*FAREROT(I,M)
          ILMOROW(I)=ILMOROW(I)+ILMOROT(I,M)*FAREROT(I,M)
          UEROW(I)=UEROW(I)+UEROT(I,M)*FAREROT(I,M)
          HBLROW(I)=HBLROW(I)+HBLROT(I,M)*FAREROT(I,M)
          DO 550 J=1,IGND
              HMFGROW(I,J)=HMFGROW(I,J)+HMFGROT(I,M,J)*FAREROT(I,M)        
              HTCROW(I,J)=HTCROW(I,J)+HTCROT(I,M,J)*FAREROT(I,M)        
              QFCROW(I,J)=QFCROW(I,J)+QFCROT(I,M,J)*FAREROT(I,M)        
              GFLXROW(I,J)=GFLXROW(I,J)+GFLXROT(I,M,J)*FAREROT(I,M)        
550       CONTINUE
575   CONTINUE
600   CONTINUE
C
C=======================================================================
C     * ACCUMULATE OUTPUT DATA FOR DIURNALLY AVERAGED FIELDS.

      DO 675 I=1,NLTEST
      DO 650 M=1,NMTEST
          PREACC(I)=PREACC(I)+PREROW(I)*FAREROT(I,M)*DELT
          GTACC(I)=GTACC(I)+GTROT(I,M)*FAREROT(I,M)
          QEVPACC(I)=QEVPACC(I)+QEVPROT(I,M)*FAREROT(I,M)
          EVAPACC(I)=EVAPACC(I)+QFSROT(I,M)*FAREROT(I,M)*DELT
          HFSACC(I)=HFSACC(I)+HFSROT(I,M)*FAREROT(I,M)
          HMFNACC(I)=HMFNACC(I)+HMFNROT(I,M)*FAREROT(I,M)
          ROFACC(I)=ROFACC(I)+ROFROT(I,M)*FAREROT(I,M)*DELT
          OVRACC(I)=OVRACC(I)+ROFOROT(I,M)*FAREROT(I,M)*DELT
          WTBLACC(I)=WTBLACC(I)+WTABROT(I,M)*FAREROT(I,M)
          DO 625 J=1,IGND
              TBARACC(I,J)=TBARACC(I,J)+TBARROT(I,M,J)*FAREROT(I,M)
              THLQACC(I,J)=THLQACC(I,J)+THLQROT(I,M,J)*FAREROT(I,M)
              THICACC(I,J)=THICACC(I,J)+THICROT(I,M,J)*FAREROT(I,M)
              THALACC(I,J)=THALACC(I,J)+(THLQROT(I,M,J)+THICROT(I,M,J))
     1                    *FAREROT(I,M)
625       CONTINUE
          ALVSACC(I)=ALVSACC(I)+ALVSROT(I,M)*FAREROT(I,M)*FSVHROW(I)
          ALIRACC(I)=ALIRACC(I)+ALIRROT(I,M)*FAREROT(I,M)*FSIHROW(I)
          IF(SNOROT(I,M).GT.0.0) THEN
              RHOSACC(I)=RHOSACC(I)+RHOSROT(I,M)*FAREROT(I,M)
              TSNOACC(I)=TSNOACC(I)+TSNOROT(I,M)*FAREROT(I,M)
              WSNOACC(I)=WSNOACC(I)+WSNOROT(I,M)*FAREROT(I,M)
              SNOARE(I)=SNOARE(I)+FAREROT(I,M)
          ENDIF
          IF(TCANROT(I,M).GT.0.5) THEN
              TCANACC(I)=TCANACC(I)+TCANROT(I,M)*FAREROT(I,M)
              CANARE(I)=CANARE(I)+FAREROT(I,M)
          ENDIF
          SNOACC(I)=SNOACC(I)+SNOROT(I,M)*FAREROT(I,M)
          RCANACC(I)=RCANACC(I)+RCANROT(I,M)*FAREROT(I,M)
          SCANACC(I)=SCANACC(I)+SCANROT(I,M)*FAREROT(I,M)
          GROACC(I)=GROACC(I)+GROROT(I,M)*FAREROT(I,M)
          FSINACC(I)=FSINACC(I)+FSDOWN*FAREROT(I,M)
          FLINACC(I)=FLINACC(I)+FDLROW(I)*FAREROT(I,M)
          FLUTACC(I)=FLUTACC(I)+SBC*GTROT(I,M)**4*FAREROT(I,M)
          TAACC(I)=TAACC(I)+TAROW(I)*FAREROT(I,M)
          UVACC(I)=UVACC(I)+UVROW(I)*FAREROT(I,M)
          PRESACC(I)=PRESACC(I)+PRESROW(I)*FAREROT(I,M)
          QAACC(I)=QAACC(I)+QAROW(I)*FAREROT(I,M)
650   CONTINUE
675   CONTINUE
C
C     * CALCULATE AND PRINT DAILY AVERAGES.
C 
      IF(NCOUNT.EQ.NDAY) THEN

      DO 800 I=1,NLTEST
          PREACC(I)=PREACC(I)
          GTACC(I)=GTACC(I)/REAL(NDAY)
          QEVPACC(I)=QEVPACC(I)/REAL(NDAY)
          EVAPACC(I)=EVAPACC(I)
          HFSACC(I)=HFSACC(I)/REAL(NDAY)
          HMFNACC(I)=HMFNACC(I)/REAL(NDAY)
          ROFACC(I)=ROFACC(I)
          OVRACC(I)=OVRACC(I)
          WTBLACC(I)=WTBLACC(I)/REAL(NDAY)
          DO 725 J=1,IGND
              TBARACC(I,J)=TBARACC(I,J)/REAL(NDAY)
              THLQACC(I,J)=THLQACC(I,J)/REAL(NDAY)
              THICACC(I,J)=THICACC(I,J)/REAL(NDAY)
              THALACC(I,J)=THALACC(I,J)/REAL(NDAY)
725       CONTINUE
          IF(FSINACC(I).GT.0.0) THEN
              ALVSACC(I)=ALVSACC(I)/(FSINACC(I)*0.5)
              ALIRACC(I)=ALIRACC(I)/(FSINACC(I)*0.5)
          ELSE
              ALVSACC(I)=0.0
              ALIRACC(I)=0.0
          ENDIF
          IF(SNOARE(I).GT.0.0) THEN
              RHOSACC(I)=RHOSACC(I)/SNOARE(I)
              TSNOACC(I)=TSNOACC(I)/SNOARE(I)
              WSNOACC(I)=WSNOACC(I)/SNOARE(I)
          ENDIF
          IF(CANARE(I).GT.0.0) THEN
              TCANACC(I)=TCANACC(I)/CANARE(I)
          ENDIF
          SNOACC(I)=SNOACC(I)/REAL(NDAY)
          RCANACC(I)=RCANACC(I)/REAL(NDAY)
          SCANACC(I)=SCANACC(I)/REAL(NDAY)
          GROACC(I)=GROACC(I)/REAL(NDAY)
          FSINACC(I)=FSINACC(I)/REAL(NDAY)
          FLINACC(I)=FLINACC(I)/REAL(NDAY)
          FLUTACC(I)=FLUTACC(I)/REAL(NDAY)
          TAACC(I)=TAACC(I)/REAL(NDAY)
          UVACC(I)=UVACC(I)/REAL(NDAY)
          PRESACC(I)=PRESACC(I)/REAL(NDAY)
          QAACC(I)=QAACC(I)/REAL(NDAY)

              ALTOT=(ALVSACC(I)+ALIRACC(I))/2.0
              FSSTAR=FSINACC(I)*(1.-ALTOT)
              FLSTAR=FLINACC(I)-FLUTACC(I)
              QH=HFSACC(I)
              QE=QEVPACC(I)
              BEG=FSSTAR+FLSTAR-QH-QE
              SNOMLT=HMFNACC(I)
              IF(RHOSACC(I).GT.0.0) THEN
                  ZSN=SNOACC(I)/RHOSACC(I)
              ELSE
                  ZSN=0.0
              ENDIF
              IF(TCANACC(I).GT.0.01) THEN
                  TCN=TCANACC(I)-TFREZ
              ELSE
                  TCN=0.0
              ENDIF
              IF(TSNOACC(I).GT.0.01) THEN
                  TSN=TSNOACC(I)-TFREZ
              ELSE
                  TSN=0.0
              ENDIF
              GTOUT=GTACC(I)-TFREZ
              WRITE(61,6100) IDAY,IYEAR,FSSTAR,FLSTAR,QH,QE,SNOMLT,
     1                       BEG,GTOUT,SNOACC(I),RHOSACC(I),
     2                       WSNOACC(I),ALTOT,ROFACC(I),CUMSNO
              IF(IGND.GT.3) THEN
                  WRITE(62,6201) IDAY,IYEAR,(TBARACC(I,J)-TFREZ,
     1                       THLQACC(I,J),THICACC(I,J),J=1,5)
                  WRITE(63,6201) IDAY,IYEAR,(TBARACC(I,J)-TFREZ,
     1                       THLQACC(I,J),THICACC(I,J),J=6,10)
              ELSE
                  WRITE(62,6200) IDAY,IYEAR,(TBARACC(I,J)-TFREZ,
     1                       THLQACC(I,J),THICACC(I,J),J=1,3),
     2                       TCN,RCANACC(I),SCANACC(I),TSN,ZSN
                  WRITE(63,6300) IDAY,IYEAR,FSINACC(I),FLINACC(I),
     1                       TAACC(I)-TFREZ,UVACC(I),PRESACC(I),
     2                       QAACC(I),PREACC(I),EVAPACC(I)
              ENDIF
C
C     * RESET ACCUMULATOR ARRAYS.
C
          PREACC(I)=0.
          GTACC(I)=0.
          QEVPACC(I)=0.
          HFSACC(I)=0.
          HMFNACC(I)=0.
          ROFACC(I)=0.
          SNOACC(I)=0.
          CANARE(I)=0.
          SNOARE(I)=0.
          OVRACC(I)=0.
          WTBLACC(I)=0.
          DO 750 J=1,IGND
              TBARACC(I,J)=0.
              THLQACC(I,J)=0.
              THICACC(I,J)=0.
              THALACC(I,J)=0.
750       CONTINUE
          ALVSACC(I)=0.
          ALIRACC(I)=0.
          RHOSACC(I)=0.
          TSNOACC(I)=0.
          WSNOACC(I)=0.
          TCANACC(I)=0.
          RCANACC(I)=0.
          SCANACC(I)=0.
          GROACC(I)=0.
          FSINACC(I)=0.
          FLINACC(I)=0.
          TAACC(I)=0.
          UVACC(I)=0.
          PRESACC(I)=0.
          QAACC(I)=0.
          EVAPACC(I)=0.
          FLUTACC(I)=0.
800   CONTINUE

      ENDIF

      NCOUNT=NCOUNT+1
      IF(NCOUNT.GT.NDAY) THEN
          NCOUNT=1
      ENDIF

C=======================================================================
C
      GO TO 200
999   CONTINUE
C
      DO 825 J=1,6
          ISUM(J)=0
825   CONTINUE
      DO 900 I=1,50
          WRITE(67,850) I,(ITCTGAT(1,J,I),J=1,6)
          DO 810 J=1,6
              ISUM(J)=ISUM(J)+ITCTGAT(1,J,I)
810       CONTINUE
900   CONTINUE
850   FORMAT(2X,7I10)
      WRITE(67,875) (ISUM(J),J=1,6)
875   FORMAT(2X,10X,6I10)

      STOP
      END
