SUBROUTINE SCATTER(NTYPE,NA,NML,ILMOS,JLMOS,ACLASS,GRD,GAT)

!DISTRIBUTES GAT TO GRD FORMAT FOR (CSV) FORCING DATA.

INTEGER :: NTYPE,NA,NML
INTEGER :: ILMOS(NML),JLMOS(NML)
REAL :: GRD(NA),GAT(NML),ACLASS(NA,NTYPE)

INTEGER I,J,K

GRD=0.
DO K=1,NML
    GRD(ILMOS(K))=GRD(ILMOS(K))+ACLASS(ILMOS(K),JLMOS(K))*GAT(K)
ENDDO

END SUBROUTINE
