SUBROUTINE SCATTER(NTYPE,NA,FAREA,GRD,GRU)

!PRODUCES GRD VALUES OF GRU BASED (CSV) FORCING DATA.

    INTEGER NTYPE, NA
    REAL    GRD(NA), GRU(NTYPE), FAREA(NA,NTYPE)
    
    INTEGER I,J
    
    DO I = 1, NA
       GRD(I) = 0.0
       DO J = 1, NTYPE
          GRD(I) = GRD(I) + FAREA(I,J)*GRU(J)
       ENDDO
   ENDDO

END SUBROUTINE
