      SUBROUTINE STORVAR(NF,G,NTIME,NAME,ILEV,ILG,ILAT,MAXX)
C
C     * SEP 29/08 - D.VERSEGHY. CALL SUBROUTINE GETFLD2 TO WRITE
C     *                         A FIELD G TO FILE NF IN CCCma
C     *                         STANDARD FORMAT, FIRST ASSIGNING
C     *                         THE APPROPRIATE VALUES TO THE 
C     *                         VECTOR IBUF.
C
      IMPLICIT NONE
C
C     * DECLARE VARIABLES/ARRAYS NEEDED FOR GETFLD/PUTFLD.
C
      REAL G(10088)
      INTEGER NF,NTIME,ILEV,ILG,ILAT
      INTEGER IBUF(8),IDAT(10088)
      INTEGER NC4TO8,INTEFLT,ME32O64
      INTEGER MAXX,IDUMMY,MACHINE,INTSIZE
      CHARACTER NAME*4
      LOGICAL OK

      COMMON/ICOM/IBUF,IDAT
      COMMON /MACHTYP/ MACHINE,INTSIZE
C
C     * DETERMINE THE MACHINE TYPE (PASSED TO LOW-LEVEL I/O ROUTINES).
C
      MACHINE = ME32O64(IDUMMY)
      INTSIZE = INTEFLT(IDUMMY)
C
C---------------------------------------------------------------------
C
      IBUF(1)=NC4TO8("GRID")
      IBUF(2)=NTIME
      IBUF(3)=NC4TO8(NAME)
      IBUF(4)=ILEV
      IBUF(5)=ILG
      IBUF(6)=ILAT
      IBUF(7)=1
      IBUF(8)=1
C
C       * WRITE OUT FIELD IN CCCma STANDARD FORMAT.
C
      CALL PUTFLD2(NF,G,IBUF,MAXX)
C
      END
