close all
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /fs/site2/dev/eccc/oth/nlab_west/aql000/MESH_Forecast/gem_forecasts/05KJ001/SaMESHRunShort/BASINAVG1/MESH_output_streamflow_ts_final.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/12/14 21:11:49

%% Initialize variables.
filename = '/fs/site2/dev/eccc/oth/nlab_west/aql000/MESH_Forecast/gem_forecasts/05KJ001/SaMESHRunShort/BASINAVG1/MESH_output_streamflow_ts_final.csv';
startRow = 2;

%% Format string for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: text (%s)
%	column4: text (%s)
%   column5: double (%f)
%	column6: text (%s)
%   column7: double (%f)
%	column8: text (%s)
%   column9: double (%f)
%	column10: text (%s)
%   column11: double (%f)
%	column12: text (%s)
%   column13: double (%f)
%	column14: text (%s)
%   column15: double (%f)
%	column16: text (%s)
%   column17: double (%f)
%	column18: text (%s)
%   column19: double (%f)
%	column20: text (%s)
%   column21: double (%f)
%	column22: text (%s)
%   column23: double (%f)
%	column24: text (%s)
%   column25: double (%f)
%	column26: text (%s)
%   column27: double (%f)
%	column28: text (%s)
%   column29: double (%f)
%	column30: text (%s)
%   column31: double (%f)
%	column32: text (%s)
%   column33: double (%f)
%	column34: text (%s)
%   column35: double (%f)
%	column36: text (%s)
%   column37: double (%f)
%	column38: text (%s)
%   column39: double (%f)
%	column40: text (%s)
%   column41: double (%f)
%	column42: text (%s)
%   column43: double (%f)
%	column44: text (%s)
%   column45: double (%f)
%	column46: text (%s)
%   column47: double (%f)
%	column48: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%16s%16s%16s%16s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%5s%11f%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Remove white space around all cell columns.
dataArray{1} = strtrim(dataArray{1});
dataArray{2} = strtrim(dataArray{2});
dataArray{3} = strtrim(dataArray{3});
dataArray{4} = strtrim(dataArray{4});
dataArray{6} = strtrim(dataArray{6});
dataArray{8} = strtrim(dataArray{8});
dataArray{10} = strtrim(dataArray{10});
dataArray{12} = strtrim(dataArray{12});
dataArray{14} = strtrim(dataArray{14});
dataArray{16} = strtrim(dataArray{16});
dataArray{18} = strtrim(dataArray{18});
dataArray{20} = strtrim(dataArray{20});
dataArray{22} = strtrim(dataArray{22});
dataArray{24} = strtrim(dataArray{24});
dataArray{26} = strtrim(dataArray{26});
dataArray{28} = strtrim(dataArray{28});
dataArray{30} = strtrim(dataArray{30});
dataArray{32} = strtrim(dataArray{32});
dataArray{34} = strtrim(dataArray{34});
dataArray{36} = strtrim(dataArray{36});
dataArray{38} = strtrim(dataArray{38});
dataArray{40} = strtrim(dataArray{40});
dataArray{42} = strtrim(dataArray{42});
dataArray{44} = strtrim(dataArray{44});
dataArray{46} = strtrim(dataArray{46});
dataArray{48} = strtrim(dataArray{48});

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
YEAR = dataArray{:, 1};
DAY = dataArray{:, 2};
HOUR = dataArray{:, 3};
MINS = dataArray{:, 4};
QOM = dataArray{:, 5};
EAS1 = dataArray{:, 6};
QO = dataArray{:, 7};
SIM1 = dataArray{:, 8};
QOM1 = dataArray{:, 9};
EAS2 = dataArray{:, 10};
QO1 = dataArray{:, 11};
SIM2 = dataArray{:, 12};
QOM2 = dataArray{:, 13};
EAS3 = dataArray{:, 14};
QO2 = dataArray{:, 15};
SIM3 = dataArray{:, 16};
QOM3 = dataArray{:, 17};
EAS4 = dataArray{:, 18};
QO3 = dataArray{:, 19};
SIM4 = dataArray{:, 20};
QOM4 = dataArray{:, 21};
EAS5 = dataArray{:, 22};
QO4 = dataArray{:, 23};
SIM5 = dataArray{:, 24};
QOM5 = dataArray{:, 25};
EAS6 = dataArray{:, 26};
QO5 = dataArray{:, 27};
SIM6 = dataArray{:, 28};
QOM6 = dataArray{:, 29};
EAS7 = dataArray{:, 30};
QO6 = dataArray{:, 31};
SIM7 = dataArray{:, 32};
QOM7 = dataArray{:, 33};
EAS8 = dataArray{:, 34};
QO7 = dataArray{:, 35};
SIM8 = dataArray{:, 36};
QOM8 = dataArray{:, 37};
EAS9 = dataArray{:, 38};
QO8 = dataArray{:, 39};
SIM9 = dataArray{:, 40};
QOME = dataArray{:, 41};
AS10 = dataArray{:, 42};
QOS = dataArray{:, 43};
IM10 = dataArray{:, 44};
QOME1 = dataArray{:, 45};
AS11 = dataArray{:, 46};
QOS1 = dataArray{:, 47};
IM11 = dataArray{:, 48};


%% Clear temporary variables
clearvars filename startRow formatSpec fileID dataArray ans;

time1=datenum(str2num(cell2mat(YEAR(1))),0,str2num(cell2mat(DAY(1)))+16/24);
time2=datenum(str2num(cell2mat(YEAR(end))),0,str2num(cell2mat(DAY(end)))+15.5/24);
time=linspace(time1,time2, length(YEAR))
plot(time(1:end-48*2),QO(1:end-48*2),'k-',time(end-48*2+1: end),QO(end-48*2+1:end),'g--','linewidth',2)
datetick
xlabel('Year (2017)', 'Fontsize',14)
ylabel ('Streamflow','Fontsize',14)
ylim([0 40])
title({'SaMESH Real-time Streamflow Forecast', 'for Oldman River Near the Mouth'},'Fontsize',16)
print([date '-05AG006.png'],'-dpng','-r300')