#!/bin/sh

set -ae
set -x

# DOROTHEE CHARPENTIER - 25 JUILLET 2008
#
# NOM : extrait_TJ
#
# DESCRIPTION : 
#
# Ce script permet d'extraire la temperature de l'air a 2m TJ, de
# regrouper toutes les heures d'une meme journee dans un seul fichier,
# puis de convertir la temperature en degres Celsius.

#-----------------------------------------------------------
jobname=`basename $0`
#-----------------------------------------------------------

firstdate=${first_date}
lastdate=${last_date}
repentree=$exper_path
repsortie=$repentree/BUDGET

#set +e
#eval ` cclargs \
#       -firstdate ",,,," ",,,,"\
#        "[date du debut de la simulation]"\
#       -lastdate ",,,," ",,,,"\
#        "[date de la fin de la simulation]"\
#       -repentree ",,,," ",,,,"\
#       -repsortie ",,,," ",,,,"\
#       ++ $*`
#set -e


ici=$repsortie
cd ${ici}

date=${firstdate}

while [ ${date} -ge ${firstdate} -a ${date} -le ${lastdate} ] ; do

# tic tac dans le fichier ou TJ est rassemble (TJ_Kelvin)

cat > dirfst1 <<EOF
desire(-1,"^^")
desire(-1,">>")
EOF
editfst -s ${repentree}/output_${date}/pm${date}-00-00_000 -d ${ici}/${date}_TJ_Kelvin.fst -i dirfst1

heure=1

# on rassemble tous les heures de TJ dans un meme fichier

while [ $heure -le 24 ] ; do

heuref=00${heure}
heuref=${heuref:(-3)}

cat > dirfst2 <<EOF
desire(-1,'TJ',-1,-1,-1,$heure,-1)
EOF
editfst -s ${repentree}/output_${date}/pm${date}-00-00_${heuref} -d ${ici}/${date}_TJ_Kelvin.fst -i dirfst2

heure=`expr $heure + 1`

done

# on convertit TJ de Kelvin en Celsius (TJ_Celsius)

r.diag xlin ${ici}/${date}_TJ_Kelvin.fst ${ici}/${date}_TJ_Celsius.fst <<EOF
                  1.   -273.15
EOF

aaaa=`echo $date | cut -c1-4`

if [ ! -d ${repsortie}/temperature_Kelvin ] ; then
    mkdir -m 755 -p ${repsortie}/temperature_Kelvin
fi

if [ ! -d ${repsortie}/temperature_Celsius ] ; then
    mkdir -m 755 -p ${repsortie}/temperature_Celsius
fi

if [ ! -d ${repsortie}/temperature_Kelvin/${aaaa} ] ; then
    mkdir -m 755 -p ${repsortie}/temperature_Kelvin/${aaaa}
fi

if [ ! -d ${repsortie}/temperature_Celsius/${aaaa} ] ; then
    mkdir -m 755 -p ${repsortie}/temperature_Celsius/${aaaa}
fi

cp ${ici}/${date}_TJ_Kelvin.fst ${repsortie}/temperature_Kelvin/${aaaa}
cp ${ici}/${date}_TJ_Celsius.fst ${repsortie}/temperature_Celsius/${aaaa}

rm -f ${date}_TJ_*

rm -f dirfst*

# on passe a la journee suivante

date=`r.date ${date} +24`
date=${date:0:10}

done

#-------------------------------------------
echo " $jobname " ' se termine normalement '
#-------------------------------------------
