#!/bin/sh

set -ae
set -x

# DOROTHEE CHARPENTIER - 10 SEPTEMBRE 2008
#
# NOM : extrait_TRAF
#
# DESCRIPTION : 
#
# Ce script permet d'extraire le ruissellement accumule TRAF, de
# regrouper toutes les heures d'une meme journee dans un seul fichier,
# de decumuler le champ en TRAF0.

#-----------------------------------------------------------
jobname=`basename $0`
#-----------------------------------------------------------

firstdate=${first_date}
lastdate=${last_date}
repentree=$exper_path
repsortie=$repentree/BUDGET

#set +e
#eval ` cclargs \
#       -firstdate ",,,," ",,,,"\
#        "[date du debut de la simulation]"\
#       -lastdate ",,,," ",,,,"\
#        "[date de la fin de la simulation]"\
#       -repentree ",,,," ",,,,"\
#       -repsortie ",,,," ",,,,"\
#       ++ $*`
#set -e

ici=$repsortie
cd ${ici}

date=${firstdate}

while [ ${date} -ge ${firstdate} -a ${date} -le ${lastdate} ] ; do

# tic tac dans le fichier ou TRAF est rassemble (TRAF_cum)

cat > dirfst1 <<EOF
desire(-1,"^^")
desire(-1,">>")
EOF
editfst -s ${repentree}/output_${date}/pm${date}-00-00_000 -d ${ici}/${date}_TRAF_cum.fst -i dirfst1

heure=0

# on rassemble tous les heures de TRAF dans un meme fichier

while [ $heure -le 24 ] ; do

heuref=00${heure}
heuref=${heuref:(-3)}

cat > dirfst2 <<EOF
desire(-1,'TRAF',-1,-1,-1,$heure,-1)
EOF
editfst -s ${repentree}/output_${date}/pm${date}-00-00_${heuref} -d ${ici}/${date}_TRAF_cum.fst -i dirfst2

heure=`expr $heure + 1`

done

# tic tac dans le fichier ou TRAF est decumule en TRAF0 (TRAF0_mm)

editfst -s ${ici}/${date}_TRAF_cum.fst -d ${ici}/${date}_TRAF0_mm.fst -i dirfst1

heure=1

# on decumule TRAF ; la variable s'appelle TRAF0

while [ $heure -le 24 ] ; do

heuref=00${heure}
heuref=${heuref:(-3)}

cat > dirpgsm <<EOF 
sortie(std,4000)
liree(TRAF,-1,-1,-1,${heure},-1,-1)
moinse(TRAF,-1,-1,-1,`expr ${heure} - 1`,-1,-1)
ecrits('TRAF0',-32,-1,-1,${heure},-1,-1,-1,-1,IMPRIM)
EOF
pgsm -iment ${ici}/${date}_TRAF_cum.fst -ozsrt ${ici}/${date}_TRAF0_mm.fst -i dirpgsm

heure=`expr $heure + 1`

done

aaaa=`echo $date | cut -c1-4`

if [ ! -d ${repsortie}/ruissellement_mm ] ; then
    mkdir -m 755 -p ${repsortie}/ruissellement_mm
fi

if [ ! -d ${repsortie}/ruissellement_mm/${aaaa} ] ; then
    mkdir -m 755 -p ${repsortie}/ruissellement_mm/${aaaa}
fi

cp ${ici}/${date}_TRAF0_mm.fst ${repsortie}/ruissellement_mm/${aaaa}

rm -f ${ici}/${date}_TRAF0_*

rm -f dirfst1 dirfst2 dirpgsm

# on passe a la journee suivante

date=`r.date ${date} +24`
date=${date:0:10}

done

rm -f *_TRAF_cum.fst

#-------------------------------------------
echo " $jobname " ' se termine normalement '
#-------------------------------------------
