#!/bin/sh

set -ae
set -x

# DOROTHEE CHARPENTIER - 25 JUILLET 2008
#
# NOM : extrait_PR
#
# DESCRIPTION : 
#
# Ce script permet d'extraire la precipitation accumulee PR, de
# regrouper toutes les heures d'une meme journee dans un seul fichier,
# de decumuler le champ en PR0 puis de le convertir en mm.

#-----------------------------------------------------------
jobname=`basename $0`
#-----------------------------------------------------------

firstdate=${first_date}
lastdate=${last_date}
repentree=$exper_path
repsortie=$repentree/BUDGET

#set +e
#eval ` cclargs \
#       -firstdate ",,,," ",,,,"\
#        "[date du debut de la simulation]"\
#       -lastdate ",,,," ",,,,"\
#        "[date de la fin de la simulation]"\
#       -repentree ",,,," ",,,,"\
#       -repsortie ",,,," ",,,,"\
#       ++ $*`
#set -e

ici=$repsortie
cd ${ici}

date=${firstdate}

while [ ${date} -ge ${firstdate} -a ${date} -le ${lastdate} ] ; do

# tic tac dans le fichier ou PR est rassemble (PR_cum)

cat > dirfst1 <<EOF
desire(-1,"^^")
desire(-1,">>")
EOF
editfst -s ${repentree}/output_${date}/pm${date}-00-00_000 -d ${ici}/${date}_PR_cum.fst -i dirfst1

heure=0

# on rassemble tous les heures de PR dans un meme fichier

while [ $heure -le 24 ] ; do

heuref=00${heure}
heuref=${heuref:(-3)}

cat > dirfst2 <<EOF
desire(-1,'PR',-1,-1,-1,$heure,-1)
EOF
editfst -s ${repentree}/output_${date}/pm${date}-00-00_${heuref} -d ${ici}/${date}_PR_cum.fst -i dirfst2

heure=`expr $heure + 1`

done

# tic tac dans le fichier ou PR est decumule en PR0 (PR0_m)

editfst -s ${ici}/${date}_PR_cum.fst -d ${ici}/${date}_PR0_m.fst -i dirfst1

heure=1

# on decumule PR ; la variable s'appelle PR0

while [ $heure -le 24 ] ; do

heuref=00${heure}
heuref=${heuref:(-3)}

cat > dirpgsm <<EOF 
sortie(std,4000)
liree(PR,-1,-1,-1,${heure},-1,-1)
moinse(PR,-1,-1,-1,`expr ${heure} - 1`,-1,-1)
ecrits('PR0',-32,-1,-1,${heure},-1,-1,-1,-1,IMPRIM)
EOF
pgsm -iment ${ici}/${date}_PR_cum.fst -ozsrt ${ici}/${date}_PR0_m.fst -i dirpgsm

heure=`expr $heure + 1`

done

# on convertit PRO de metre en millimetre (PR0_mm)

r.diag xlin ${ici}/${date}_PR0_m.fst ${ici}/${date}_PR0_mm.fst <<EOF
               1000.
EOF

aaaa=`echo $date | cut -c1-4`

if [ ! -d ${repsortie}/precipitation_m ] ; then
    mkdir -m 755 -p ${repsortie}/precipitation_m
fi

if [ ! -d ${repsortie}/precipitation_mm ] ; then
    mkdir -m 755 -p ${repsortie}/precipitation_mm
fi

if [ ! -d ${repsortie}/precipitation_m/${aaaa} ] ; then
    mkdir -m 755 -p ${repsortie}/precipitation_m/${aaaa}
fi

if [ ! -d ${repsortie}/precipitation_mm/${aaaa} ] ; then
    mkdir -m 755 -p ${repsortie}/precipitation_mm/${aaaa}
fi

cp ${ici}/${date}_PR0_m.fst ${repsortie}/precipitation_m/${aaaa}
cp ${ici}/${date}_PR0_mm.fst ${repsortie}/precipitation_mm/${aaaa}

rm -f ${ici}/${date}_PR0_*

rm -f dirfst1 dirfst2 dirpgsm

# on passe a la journee suivante

date=`r.date ${date} +24`
date=${date:0:10}

done

rm -f *_PR_cum.fst

#-------------------------------------------
echo " $jobname " ' se termine normalement '
#-------------------------------------------
