# ======================================================================
#		Include or header file for flowinit makefile
#               Compile with gfortran compiler
# ======================================================================

# ======================================================================
# Directory of source code
# ======================================================================
DIR_REPO=C:\SA_MESH\TRUNK

# ======================================================================
# Include the following directories in the source file searching path
# ======================================================================
VPATH=	$(DIR_REPO)\Pre_Process\RPN_flowinit\code; \
		$(DIR_REPO)\Routing_Model\RPN_watroute\code; \

# ======================================================================
# Object files needed to build
# ======================================================================

#Modules
MODULES=	area_watflood.mod ef_module.mod ef_parseutilities.mod 
OBJECTS=	area_watflood.o EF_Module.o EF_ParseUtilities.o 

#Watroute
OBJECTS+=	rdevt.o read_flow_ef.o read_resv_ef.o read_shed_ef.o \
		write_flowinit.o write_r2c.o 

#Flowinit
OBJECTS+=	fli.o flowinit.o write_lzsinit.o
