# ======================================================================
#		Include or header file for Watroute_SimStat makefile
#               Compile with gfortran compiler
# ======================================================================

# ======================================================================
# Object files needed to build watroute
# ======================================================================

# ======================================================================
# Directory of source code
# ======================================================================
DIR_REPO=C:\sa_MESH\TRUNK

# ======================================================================
# Include the following directories in the source file searching path
# ======================================================================
VPATH=	$(DIR_REPO)\Driver\MESH_Driver; \
		$(DIR_REPO)\Routing_Model\RPN_watroute\code; \

#Modules
MODULES=	area_watflood.mod ef_module.mod ef_parseutilities.mod 
OBJECTS=	area_watflood.o EF_Module.o EF_ParseUtilities.o 

#Watroute
OBJECTS+=	rdevt.o read_flow_ef.o 

#MESH_driver
OBJECTS+=	Julian_Day_ID.o NSE.o SAE.o SAEMSRT.o SAESRT.o \
		SIMSTATS.o SORT.o TEST_CSV.o
OBJECTS+=	Watroute_SimStat.o
