SUBROUTINE R2C_DATA_CMEM(DATAIN,DATAOUT,NML,NLTEST,NMTEST,NCOUNT, &
                    IMIN,ACLASS,NR2C,GRD,GAT,GRDGAT,NR2CSTATES, &
                    NLAT,XXX,YYY,XCOUNT,YCOUNT,ILMOS,JLMOS,ILG,IC,ICP1,IG, &
                       TBH,TBV,TAUH,TAUV)
 
!     * CMEM VARIABLES.
REAL    TBH(ILG,IG),   TBV(ILG,IG),   TAUH(ILG,IG), TAUV(ILG,IG)
        

INTEGER NML,NLTEST,NMTEST,NCOUNT,IMIN,NR2C,NLAT,ILG,XCOUNT,YCOUNT,IC,ICP1,IG
INTEGER XXX(NLAT),YYY(NLAT)
INTEGER ILMOS(ILG),JLMOS(ILG),IGDRGAT(ILG)
INTEGER GRD(NR2C),GAT(NR2C),GRDGAT(NR2C)

REAL    ACLASS(NLTEST,NMTEST+1)
   
INTEGER FILECOUNT,NR2CSTATES
REAL    DATAIN(ILG),DATAOUT(NR2CSTATES,XCOUNT,YCOUNT)

!> INITIALIZE DATA OUTPUT ARRAY

   DATAOUT = 0.0

!> COLLECT OUTPUT DATA
   FILECOUNT = 0

   I = 0
   
!> ATTRIBUTE 1 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = TBH(:,J)
   CALL COLLECTDATA_CMEM(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
               
! ATTRIBUTE 2 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = TBV(:,J)
   CALL COLLECTDATA_CMEM(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 3 -
   DO J = 1, IG
   I = I + 1
   DATAIN = TAUH(:,J)
   CALL COLLECTDATA_CMEM(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
! ATTRIBUTE 4 - 
   DO J = 1, IG
   I = I + 1
   DATAIN = TAUV(:,J)
   CALL COLLECTDATA_CMEM(DATAIN,DATAOUT,GRD(I),GAT(I),GRDGAT(I),FILECOUNT,NLAT,NR2CSTATES, &
                     NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                     ACLASS)
   ENDDO
   
RETURN

END

SUBROUTINE COLLECTDATA_CMEM(DATAIN,DATAOUT,GRD,GAT,GRDGAT,FILECOUNT,NLAT,NR2CSTATES, &
                       NLTEST,NMTEST,NML,ILG,ILMOS,JLMOS,XXX,YYY,XCOUNT,YCOUNT, &
                       ACLASS)

INTEGER GRD,GAT,GRDGAT,FILECOUNT,NLAT,NR2CSTATES,NLTEST,NMTEST,NML,ILG,XCOUNT,YCOUNT
INTEGER XXX(NLAT),YYY(NLAT),ILMOS(ILG),JLMOS(ILG)
REAL    ACLASS(NLTEST,NMTEST+1),DATAIN(ILG),DATAOUT(NR2CSTATES,XCOUNT,YCOUNT), &
        DATAOUTTMP(NMTEST,XCOUNT,YCOUNT)

   IF(GRD == 1)THEN
      FILECOUNT = FILECOUNT + 1
      DO I = 1, NML
         II = XXX(ILMOS(I))
         JJ = YYY(ILMOS(I))
         DATAOUT(FILECOUNT,II,JJ) = DATAOUT(FILECOUNT,II,JJ) + DATAIN(I) * ACLASS(ILMOS(I),JLMOS(I))
      END DO
   ENDIF
   
   DATAOUTTMP = 0.0
   IF(GAT == 1)THEN
      DO I = 1, NML
         II = XXX(ILMOS(I))
         JJ = YYY(ILMOS(I))
         DATAOUTTMP(JLMOS(I),II,JJ) = DATAIN(I)
      END DO
      DO J = 1, NMTEST
         FILECOUNT = FILECOUNT + 1
         DATAOUT(FILECOUNT,:,:) = DATAOUTTMP(J,:,:)
      ENDDO
   ENDIF
   
   DATAOUTTMP = 0.0
   IF(GRDGAT == 1)THEN
      DO I = 1, NML
         II = XXX(ILMOS(I))
         JJ = YYY(ILMOS(I))
         DATAOUTTMP(JLMOS(I),II,JJ) = DATAIN(I) * ACLASS(ILMOS(I),JLMOS(I))
      END DO
      DO J = 1, NMTEST
         FILECOUNT = FILECOUNT + 1
         DATAOUT(FILECOUNT,:,:) = DATAOUTTMP(J,:,:)
      ENDDO
   ENDIF
RETURN
END