SUBROUTINE WRITE_CMEM_R2C_DATA(NML,NLTEST,NMTEST,NCOUNT,IMIN,ACLASS, &
                          NLAT,XXX,YYY,XCOUNT,YCOUNT,ILMOS,JLMOS,ILG, &
                          NR2C,NR2CFILES,R2CFILEUNITSTART,GRD,GAT, &
                          GRDGAT,NR2CSTATES,R2C_ATTRIBUTES,FRAME_NO,YY, &
                          MM,DD,HH,MI,IC,ICP1,IG,TBH,TBV,TAUH,TAUV)

USE MESH_CMEM_MODULE, ONLY:CMEMFLAG, CMEMTHETA !> KCK MAY NOT NEED THESE
							
							 

INTEGER      FRAME_NO,YY,MM,DD,HH,MI
INTEGER      GRD(NR2C),GAT(NR2C),GRDGAT(NR2C)
CHARACTER(*) R2C_ATTRIBUTES(NR2C,3)

INTEGER NML,NLTEST,NMTEST,NCOUNT,IMIN,NLAT,ILG,XCOUNT,YCOUNT,IC,ICP1,IG
INTEGER XXX(NLAT),YYY(NLAT)
INTEGER ILMOS(ILG),JLMOS(ILG),IGDRGAT(ILG)

REAL ACLASS(NLTEST,NMTEST+1)
REAL DATAIN(ILG),DATAOUT(NR2CSTATES,XCOUNT,YCOUNT),DATAOUT2(XCOUNT,YCOUNT)

!     * CMEM VARIABLES.
REAL    TBH(ILG,IG),   TBV(ILG,IG),   TAUH(ILG,IG), TAUV(ILG,IG)
        

INTEGER FILECOUNT,R2CFILEUNITSTART,R2CFILEUNIT,NR2CSTATES


!>COLLECT OUTPUT DATA
CALL R2C_DATA_CMEM(DATAIN,DATAOUT,NML,NLTEST,NMTEST,NCOUNT, &
              IMIN,ACLASS,NR2C,GRD,GAT,GRDGAT,NR2CSTATES, &
              NLAT,XXX,YYY,XCOUNT,YCOUNT,ILMOS,JLMOS,ILG,IC,ICP1,IG, &
                       TBH,TBV,TAUH,TAUV)

FILECOUNT = 0
R2CFILEUNIT = R2CFILEUNITSTART
DO N = 1, NR2C
   IF(GRD(N) == 1)THEN
      FILECOUNT = FILECOUNT + 1
      R2CFILEUNIT = R2CFILEUNIT + 1
      WRITE(R2CFILEUNIT,9000)':Frame',FRAME_NO,FRAME_NO,YY,MM,DD,HH,MI
      DO J = 1, YCOUNT
         WRITE(R2CFILEUNIT,'(999(F12.6))')(DATAOUT(FILECOUNT,I,J),I=1,XCOUNT)
      ENDDO
      WRITE(R2CFILEUNIT,'(A)')':EndFrame'
   ENDIF
   
   IF(GAT(N) == 1)THEN
      DO K = 1, NMTEST
         FILECOUNT = FILECOUNT + 1
         R2CFILEUNIT = R2CFILEUNIT + 1
         WRITE(R2CFILEUNIT,9000)':Frame',FRAME_NO,FRAME_NO,YY,MM,DD,HH,MI
         DO J = 1, YCOUNT
            WRITE(R2CFILEUNIT,'(999(F12.6))')(DATAOUT(FILECOUNT,I,J),I=1,XCOUNT)
         ENDDO
         WRITE(R2CFILEUNIT,'(A)')':EndFrame'
     ENDDO
   ENDIF
   
   IF(GRDGAT(N) == 1)THEN
      DO K = 1, NMTEST
         FILECOUNT = FILECOUNT + 1
         R2CFILEUNIT = R2CFILEUNIT + 1
         WRITE(R2CFILEUNIT,9000)':Frame',FRAME_NO,FRAME_NO,YY,MM,DD,HH,MI
         DO J = 1, YCOUNT
            WRITE(R2CFILEUNIT,'(999(F12.6))')(DATAOUT(FILECOUNT,I,J),I=1,XCOUNT)
         ENDDO
         WRITE(R2CFILEUNIT,'(A)')':EndFrame'
      ENDDO
   ENDIF
ENDDO

9000 FORMAT(A6,2I10,3X,'"',I4,'/',I2.2,'/',I2.2,1X,I2.2,':',I2.2,':00.000"')

RETURN
END